// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: applications.sql

package repository

import (
	"context"
	"database/sql"
	"encoding/json"

	"github.com/google/uuid"
)

const cancelApplication = `-- name: CancelApplication :one
UPDATE applications
SET status = 'cancelled', cancelled_at = now(), cancel_reason = $2, updated_at = now()
WHERE id = $1
RETURNING id, tenant_id, external_id, status, signing_round, signer_role, callback_url, callback_secret, cancelled_at, cancel_reason, created_at, updated_at
`

type CancelApplicationParams struct {
	ID           uuid.UUID      `json:"id"`
	CancelReason sql.NullString `json:"cancel_reason"`
}

func (q *Queries) CancelApplication(ctx context.Context, arg CancelApplicationParams) (Application, error) {
	row := q.db.QueryRowContext(ctx, cancelApplication, arg.ID, arg.CancelReason)
	var i Application
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ExternalID,
		&i.Status,
		&i.SigningRound,
		&i.SignerRole,
		&i.CallbackUrl,
		&i.CallbackSecret,
		&i.CancelledAt,
		&i.CancelReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createApplication = `-- name: CreateApplication :one
INSERT INTO applications (
    tenant_id, external_id, status, signing_round, signer_role,
    callback_url, callback_secret
) VALUES (
    $1, $2, 'active', 1, $3, $4, $5
)
RETURNING id, tenant_id, external_id, status, signing_round, signer_role, callback_url, callback_secret, cancelled_at, cancel_reason, created_at, updated_at
`

type CreateApplicationParams struct {
	TenantID       uuid.UUID      `json:"tenant_id"`
	ExternalID     string         `json:"external_id"`
	SignerRole     string         `json:"signer_role"`
	CallbackUrl    sql.NullString `json:"callback_url"`
	CallbackSecret sql.NullString `json:"callback_secret"`
}

func (q *Queries) CreateApplication(ctx context.Context, arg CreateApplicationParams) (Application, error) {
	row := q.db.QueryRowContext(ctx, createApplication,
		arg.TenantID,
		arg.ExternalID,
		arg.SignerRole,
		arg.CallbackUrl,
		arg.CallbackSecret,
	)
	var i Application
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ExternalID,
		&i.Status,
		&i.SigningRound,
		&i.SignerRole,
		&i.CallbackUrl,
		&i.CallbackSecret,
		&i.CancelledAt,
		&i.CancelReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createApplicationDocument = `-- name: CreateApplicationDocument :one
INSERT INTO application_documents (
    application_id, document_name, version, signing_round,
    source_url, target_url, target_s3_key, status
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, 'pending'
)
RETURNING id, application_id, document_id, document_name, version, signing_round, source_url, target_url, target_s3_key, status, superseded_by, upload_attempts, last_error, uploaded_at, created_at
`

type CreateApplicationDocumentParams struct {
	ApplicationID uuid.UUID      `json:"application_id"`
	DocumentName  string         `json:"document_name"`
	Version       int32          `json:"version"`
	SigningRound  int32          `json:"signing_round"`
	SourceUrl     string         `json:"source_url"`
	TargetUrl     sql.NullString `json:"target_url"`
	TargetS3Key   sql.NullString `json:"target_s3_key"`
}

func (q *Queries) CreateApplicationDocument(ctx context.Context, arg CreateApplicationDocumentParams) (ApplicationDocument, error) {
	row := q.db.QueryRowContext(ctx, createApplicationDocument,
		arg.ApplicationID,
		arg.DocumentName,
		arg.Version,
		arg.SigningRound,
		arg.SourceUrl,
		arg.TargetUrl,
		arg.TargetS3Key,
	)
	var i ApplicationDocument
	err := row.Scan(
		&i.ID,
		&i.ApplicationID,
		&i.DocumentID,
		&i.DocumentName,
		&i.Version,
		&i.SigningRound,
		&i.SourceUrl,
		&i.TargetUrl,
		&i.TargetS3Key,
		&i.Status,
		&i.SupersededBy,
		&i.UploadAttempts,
		&i.LastError,
		&i.UploadedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createApplicationWebhook = `-- name: CreateApplicationWebhook :one
INSERT INTO application_webhooks (
    application_id, event_type, payload, hmac_signature, status, next_attempt_at
) VALUES (
    $1, $2, $3, $4, 'pending', now()
)
RETURNING id, application_id, event_type, payload, hmac_signature, status, attempts, next_attempt_at, last_attempt_at, delivered_at, created_at
`

type CreateApplicationWebhookParams struct {
	ApplicationID uuid.UUID       `json:"application_id"`
	EventType     string          `json:"event_type"`
	Payload       json.RawMessage `json:"payload"`
	HmacSignature sql.NullString  `json:"hmac_signature"`
}

func (q *Queries) CreateApplicationWebhook(ctx context.Context, arg CreateApplicationWebhookParams) (ApplicationWebhook, error) {
	row := q.db.QueryRowContext(ctx, createApplicationWebhook,
		arg.ApplicationID,
		arg.EventType,
		arg.Payload,
		arg.HmacSignature,
	)
	var i ApplicationWebhook
	err := row.Scan(
		&i.ID,
		&i.ApplicationID,
		&i.EventType,
		&i.Payload,
		&i.HmacSignature,
		&i.Status,
		&i.Attempts,
		&i.NextAttemptAt,
		&i.LastAttemptAt,
		&i.DeliveredAt,
		&i.CreatedAt,
	)
	return i, err
}

const findPreviousVersions = `-- name: FindPreviousVersions :many
SELECT id, application_id, document_id, document_name, version, signing_round, source_url, target_url, target_s3_key, status, superseded_by, upload_attempts, last_error, uploaded_at, created_at FROM application_documents
WHERE application_id = $1 AND document_name = $2 AND status != 'superseded'
ORDER BY version
`

type FindPreviousVersionsParams struct {
	ApplicationID uuid.UUID `json:"application_id"`
	DocumentName  string    `json:"document_name"`
}

func (q *Queries) FindPreviousVersions(ctx context.Context, arg FindPreviousVersionsParams) ([]ApplicationDocument, error) {
	rows, err := q.db.QueryContext(ctx, findPreviousVersions, arg.ApplicationID, arg.DocumentName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ApplicationDocument
	for rows.Next() {
		var i ApplicationDocument
		if err := rows.Scan(
			&i.ID,
			&i.ApplicationID,
			&i.DocumentID,
			&i.DocumentName,
			&i.Version,
			&i.SigningRound,
			&i.SourceUrl,
			&i.TargetUrl,
			&i.TargetS3Key,
			&i.Status,
			&i.SupersededBy,
			&i.UploadAttempts,
			&i.LastError,
			&i.UploadedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getApplicationByExternalID = `-- name: GetApplicationByExternalID :one
SELECT id, tenant_id, external_id, status, signing_round, signer_role, callback_url, callback_secret, cancelled_at, cancel_reason, created_at, updated_at FROM applications
WHERE tenant_id = $1 AND external_id = $2
`

type GetApplicationByExternalIDParams struct {
	TenantID   uuid.UUID `json:"tenant_id"`
	ExternalID string    `json:"external_id"`
}

func (q *Queries) GetApplicationByExternalID(ctx context.Context, arg GetApplicationByExternalIDParams) (Application, error) {
	row := q.db.QueryRowContext(ctx, getApplicationByExternalID, arg.TenantID, arg.ExternalID)
	var i Application
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ExternalID,
		&i.Status,
		&i.SigningRound,
		&i.SignerRole,
		&i.CallbackUrl,
		&i.CallbackSecret,
		&i.CancelledAt,
		&i.CancelReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getApplicationByID = `-- name: GetApplicationByID :one
SELECT id, tenant_id, external_id, status, signing_round, signer_role, callback_url, callback_secret, cancelled_at, cancel_reason, created_at, updated_at FROM applications
WHERE id = $1 AND tenant_id = $2
`

type GetApplicationByIDParams struct {
	ID       uuid.UUID `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

func (q *Queries) GetApplicationByID(ctx context.Context, arg GetApplicationByIDParams) (Application, error) {
	row := q.db.QueryRowContext(ctx, getApplicationByID, arg.ID, arg.TenantID)
	var i Application
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ExternalID,
		&i.Status,
		&i.SigningRound,
		&i.SignerRole,
		&i.CallbackUrl,
		&i.CallbackSecret,
		&i.CancelledAt,
		&i.CancelReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getApplicationDocumentByID = `-- name: GetApplicationDocumentByID :one
SELECT id, application_id, document_id, document_name, version, signing_round, source_url, target_url, target_s3_key, status, superseded_by, upload_attempts, last_error, uploaded_at, created_at FROM application_documents
WHERE id = $1
`

func (q *Queries) GetApplicationDocumentByID(ctx context.Context, id uuid.UUID) (ApplicationDocument, error) {
	row := q.db.QueryRowContext(ctx, getApplicationDocumentByID, id)
	var i ApplicationDocument
	err := row.Scan(
		&i.ID,
		&i.ApplicationID,
		&i.DocumentID,
		&i.DocumentName,
		&i.Version,
		&i.SigningRound,
		&i.SourceUrl,
		&i.TargetUrl,
		&i.TargetS3Key,
		&i.Status,
		&i.SupersededBy,
		&i.UploadAttempts,
		&i.LastError,
		&i.UploadedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getPendingFetchDocuments = `-- name: GetPendingFetchDocuments :many
SELECT id, application_id, document_id, document_name, version, signing_round, source_url, target_url, target_s3_key, status, superseded_by, upload_attempts, last_error, uploaded_at, created_at FROM application_documents
WHERE status = 'pending'
ORDER BY created_at
LIMIT $1
`

func (q *Queries) GetPendingFetchDocuments(ctx context.Context, limit int32) ([]ApplicationDocument, error) {
	rows, err := q.db.QueryContext(ctx, getPendingFetchDocuments, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ApplicationDocument
	for rows.Next() {
		var i ApplicationDocument
		if err := rows.Scan(
			&i.ID,
			&i.ApplicationID,
			&i.DocumentID,
			&i.DocumentName,
			&i.Version,
			&i.SigningRound,
			&i.SourceUrl,
			&i.TargetUrl,
			&i.TargetS3Key,
			&i.Status,
			&i.SupersededBy,
			&i.UploadAttempts,
			&i.LastError,
			&i.UploadedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPendingWebhooks = `-- name: GetPendingWebhooks :many
SELECT aw.id, aw.application_id, aw.event_type, aw.payload, aw.hmac_signature, aw.status, aw.attempts, aw.next_attempt_at, aw.last_attempt_at, aw.delivered_at, aw.created_at FROM application_webhooks aw
WHERE (aw.status = 'pending' OR (aw.status = 'failed' AND aw.attempts < 5))
  AND (aw.next_attempt_at IS NULL OR aw.next_attempt_at <= now())
ORDER BY aw.created_at
LIMIT 50
`

func (q *Queries) GetPendingWebhooks(ctx context.Context) ([]ApplicationWebhook, error) {
	rows, err := q.db.QueryContext(ctx, getPendingWebhooks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ApplicationWebhook
	for rows.Next() {
		var i ApplicationWebhook
		if err := rows.Scan(
			&i.ID,
			&i.ApplicationID,
			&i.EventType,
			&i.Payload,
			&i.HmacSignature,
			&i.Status,
			&i.Attempts,
			&i.NextAttemptAt,
			&i.LastAttemptAt,
			&i.DeliveredAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const incrementUploadAttempts = `-- name: IncrementUploadAttempts :one
UPDATE application_documents
SET upload_attempts = upload_attempts + 1, last_error = $2
WHERE id = $1
RETURNING id, application_id, document_id, document_name, version, signing_round, source_url, target_url, target_s3_key, status, superseded_by, upload_attempts, last_error, uploaded_at, created_at
`

type IncrementUploadAttemptsParams struct {
	ID        uuid.UUID      `json:"id"`
	LastError sql.NullString `json:"last_error"`
}

func (q *Queries) IncrementUploadAttempts(ctx context.Context, arg IncrementUploadAttemptsParams) (ApplicationDocument, error) {
	row := q.db.QueryRowContext(ctx, incrementUploadAttempts, arg.ID, arg.LastError)
	var i ApplicationDocument
	err := row.Scan(
		&i.ID,
		&i.ApplicationID,
		&i.DocumentID,
		&i.DocumentName,
		&i.Version,
		&i.SigningRound,
		&i.SourceUrl,
		&i.TargetUrl,
		&i.TargetS3Key,
		&i.Status,
		&i.SupersededBy,
		&i.UploadAttempts,
		&i.LastError,
		&i.UploadedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listActiveApplicationDocuments = `-- name: ListActiveApplicationDocuments :many
SELECT id, application_id, document_id, document_name, version, signing_round, source_url, target_url, target_s3_key, status, superseded_by, upload_attempts, last_error, uploaded_at, created_at FROM application_documents
WHERE application_id = $1 AND signing_round = $2 AND status != 'superseded'
ORDER BY created_at
`

type ListActiveApplicationDocumentsParams struct {
	ApplicationID uuid.UUID `json:"application_id"`
	SigningRound  int32     `json:"signing_round"`
}

func (q *Queries) ListActiveApplicationDocuments(ctx context.Context, arg ListActiveApplicationDocumentsParams) ([]ApplicationDocument, error) {
	rows, err := q.db.QueryContext(ctx, listActiveApplicationDocuments, arg.ApplicationID, arg.SigningRound)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ApplicationDocument
	for rows.Next() {
		var i ApplicationDocument
		if err := rows.Scan(
			&i.ID,
			&i.ApplicationID,
			&i.DocumentID,
			&i.DocumentName,
			&i.Version,
			&i.SigningRound,
			&i.SourceUrl,
			&i.TargetUrl,
			&i.TargetS3Key,
			&i.Status,
			&i.SupersededBy,
			&i.UploadAttempts,
			&i.LastError,
			&i.UploadedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listApplicationDocuments = `-- name: ListApplicationDocuments :many
SELECT id, application_id, document_id, document_name, version, signing_round, source_url, target_url, target_s3_key, status, superseded_by, upload_attempts, last_error, uploaded_at, created_at FROM application_documents
WHERE application_id = $1
ORDER BY created_at
`

func (q *Queries) ListApplicationDocuments(ctx context.Context, applicationID uuid.UUID) ([]ApplicationDocument, error) {
	rows, err := q.db.QueryContext(ctx, listApplicationDocuments, applicationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ApplicationDocument
	for rows.Next() {
		var i ApplicationDocument
		if err := rows.Scan(
			&i.ID,
			&i.ApplicationID,
			&i.DocumentID,
			&i.DocumentName,
			&i.Version,
			&i.SigningRound,
			&i.SourceUrl,
			&i.TargetUrl,
			&i.TargetS3Key,
			&i.Status,
			&i.SupersededBy,
			&i.UploadAttempts,
			&i.LastError,
			&i.UploadedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markApplicationDocumentUploaded = `-- name: MarkApplicationDocumentUploaded :one
UPDATE application_documents
SET status = 'uploaded', uploaded_at = now()
WHERE id = $1
RETURNING id, application_id, document_id, document_name, version, signing_round, source_url, target_url, target_s3_key, status, superseded_by, upload_attempts, last_error, uploaded_at, created_at
`

func (q *Queries) MarkApplicationDocumentUploaded(ctx context.Context, id uuid.UUID) (ApplicationDocument, error) {
	row := q.db.QueryRowContext(ctx, markApplicationDocumentUploaded, id)
	var i ApplicationDocument
	err := row.Scan(
		&i.ID,
		&i.ApplicationID,
		&i.DocumentID,
		&i.DocumentName,
		&i.Version,
		&i.SigningRound,
		&i.SourceUrl,
		&i.TargetUrl,
		&i.TargetS3Key,
		&i.Status,
		&i.SupersededBy,
		&i.UploadAttempts,
		&i.LastError,
		&i.UploadedAt,
		&i.CreatedAt,
	)
	return i, err
}

const supersedeApplicationDocument = `-- name: SupersedeApplicationDocument :one
UPDATE application_documents
SET status = 'superseded', superseded_by = $2
WHERE id = $1
RETURNING id, application_id, document_id, document_name, version, signing_round, source_url, target_url, target_s3_key, status, superseded_by, upload_attempts, last_error, uploaded_at, created_at
`

type SupersedeApplicationDocumentParams struct {
	ID           uuid.UUID     `json:"id"`
	SupersededBy uuid.NullUUID `json:"superseded_by"`
}

func (q *Queries) SupersedeApplicationDocument(ctx context.Context, arg SupersedeApplicationDocumentParams) (ApplicationDocument, error) {
	row := q.db.QueryRowContext(ctx, supersedeApplicationDocument, arg.ID, arg.SupersededBy)
	var i ApplicationDocument
	err := row.Scan(
		&i.ID,
		&i.ApplicationID,
		&i.DocumentID,
		&i.DocumentName,
		&i.Version,
		&i.SigningRound,
		&i.SourceUrl,
		&i.TargetUrl,
		&i.TargetS3Key,
		&i.Status,
		&i.SupersededBy,
		&i.UploadAttempts,
		&i.LastError,
		&i.UploadedAt,
		&i.CreatedAt,
	)
	return i, err
}

const updateApplicationDocumentAfterFetch = `-- name: UpdateApplicationDocumentAfterFetch :one
UPDATE application_documents
SET document_id = $2, status = 'ready'
WHERE id = $1
RETURNING id, application_id, document_id, document_name, version, signing_round, source_url, target_url, target_s3_key, status, superseded_by, upload_attempts, last_error, uploaded_at, created_at
`

type UpdateApplicationDocumentAfterFetchParams struct {
	ID         uuid.UUID     `json:"id"`
	DocumentID uuid.NullUUID `json:"document_id"`
}

func (q *Queries) UpdateApplicationDocumentAfterFetch(ctx context.Context, arg UpdateApplicationDocumentAfterFetchParams) (ApplicationDocument, error) {
	row := q.db.QueryRowContext(ctx, updateApplicationDocumentAfterFetch, arg.ID, arg.DocumentID)
	var i ApplicationDocument
	err := row.Scan(
		&i.ID,
		&i.ApplicationID,
		&i.DocumentID,
		&i.DocumentName,
		&i.Version,
		&i.SigningRound,
		&i.SourceUrl,
		&i.TargetUrl,
		&i.TargetS3Key,
		&i.Status,
		&i.SupersededBy,
		&i.UploadAttempts,
		&i.LastError,
		&i.UploadedAt,
		&i.CreatedAt,
	)
	return i, err
}

const updateApplicationDocumentStatus = `-- name: UpdateApplicationDocumentStatus :one
UPDATE application_documents
SET status = $2, last_error = $3
WHERE id = $1
RETURNING id, application_id, document_id, document_name, version, signing_round, source_url, target_url, target_s3_key, status, superseded_by, upload_attempts, last_error, uploaded_at, created_at
`

type UpdateApplicationDocumentStatusParams struct {
	ID        uuid.UUID      `json:"id"`
	Status    string         `json:"status"`
	LastError sql.NullString `json:"last_error"`
}

func (q *Queries) UpdateApplicationDocumentStatus(ctx context.Context, arg UpdateApplicationDocumentStatusParams) (ApplicationDocument, error) {
	row := q.db.QueryRowContext(ctx, updateApplicationDocumentStatus, arg.ID, arg.Status, arg.LastError)
	var i ApplicationDocument
	err := row.Scan(
		&i.ID,
		&i.ApplicationID,
		&i.DocumentID,
		&i.DocumentName,
		&i.Version,
		&i.SigningRound,
		&i.SourceUrl,
		&i.TargetUrl,
		&i.TargetS3Key,
		&i.Status,
		&i.SupersededBy,
		&i.UploadAttempts,
		&i.LastError,
		&i.UploadedAt,
		&i.CreatedAt,
	)
	return i, err
}

const updateApplicationDocumentTargetURL = `-- name: UpdateApplicationDocumentTargetURL :one
UPDATE application_documents
SET target_url = $2
WHERE id = $1
RETURNING id, application_id, document_id, document_name, version, signing_round, source_url, target_url, target_s3_key, status, superseded_by, upload_attempts, last_error, uploaded_at, created_at
`

type UpdateApplicationDocumentTargetURLParams struct {
	ID        uuid.UUID      `json:"id"`
	TargetUrl sql.NullString `json:"target_url"`
}

func (q *Queries) UpdateApplicationDocumentTargetURL(ctx context.Context, arg UpdateApplicationDocumentTargetURLParams) (ApplicationDocument, error) {
	row := q.db.QueryRowContext(ctx, updateApplicationDocumentTargetURL, arg.ID, arg.TargetUrl)
	var i ApplicationDocument
	err := row.Scan(
		&i.ID,
		&i.ApplicationID,
		&i.DocumentID,
		&i.DocumentName,
		&i.Version,
		&i.SigningRound,
		&i.SourceUrl,
		&i.TargetUrl,
		&i.TargetS3Key,
		&i.Status,
		&i.SupersededBy,
		&i.UploadAttempts,
		&i.LastError,
		&i.UploadedAt,
		&i.CreatedAt,
	)
	return i, err
}

const updateApplicationStatus = `-- name: UpdateApplicationStatus :one
UPDATE applications
SET status = $2, signing_round = $3, signer_role = $4, callback_url = COALESCE($5, callback_url),
    callback_secret = COALESCE($6, callback_secret), updated_at = now()
WHERE id = $1
RETURNING id, tenant_id, external_id, status, signing_round, signer_role, callback_url, callback_secret, cancelled_at, cancel_reason, created_at, updated_at
`

type UpdateApplicationStatusParams struct {
	ID             uuid.UUID      `json:"id"`
	Status         string         `json:"status"`
	SigningRound   int32          `json:"signing_round"`
	SignerRole     string         `json:"signer_role"`
	CallbackUrl    sql.NullString `json:"callback_url"`
	CallbackSecret sql.NullString `json:"callback_secret"`
}

func (q *Queries) UpdateApplicationStatus(ctx context.Context, arg UpdateApplicationStatusParams) (Application, error) {
	row := q.db.QueryRowContext(ctx, updateApplicationStatus,
		arg.ID,
		arg.Status,
		arg.SigningRound,
		arg.SignerRole,
		arg.CallbackUrl,
		arg.CallbackSecret,
	)
	var i Application
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ExternalID,
		&i.Status,
		&i.SigningRound,
		&i.SignerRole,
		&i.CallbackUrl,
		&i.CallbackSecret,
		&i.CancelledAt,
		&i.CancelReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateWebhookStatus = `-- name: UpdateWebhookStatus :one
UPDATE application_webhooks
SET status = $2, attempts = $3, last_attempt_at = $4,
    delivered_at = $5, next_attempt_at = $6
WHERE id = $1
RETURNING id, application_id, event_type, payload, hmac_signature, status, attempts, next_attempt_at, last_attempt_at, delivered_at, created_at
`

type UpdateWebhookStatusParams struct {
	ID            uuid.UUID    `json:"id"`
	Status        string       `json:"status"`
	Attempts      int32        `json:"attempts"`
	LastAttemptAt sql.NullTime `json:"last_attempt_at"`
	DeliveredAt   sql.NullTime `json:"delivered_at"`
	NextAttemptAt sql.NullTime `json:"next_attempt_at"`
}

func (q *Queries) UpdateWebhookStatus(ctx context.Context, arg UpdateWebhookStatusParams) (ApplicationWebhook, error) {
	row := q.db.QueryRowContext(ctx, updateWebhookStatus,
		arg.ID,
		arg.Status,
		arg.Attempts,
		arg.LastAttemptAt,
		arg.DeliveredAt,
		arg.NextAttemptAt,
	)
	var i ApplicationWebhook
	err := row.Scan(
		&i.ID,
		&i.ApplicationID,
		&i.EventType,
		&i.Payload,
		&i.HmacSignature,
		&i.Status,
		&i.Attempts,
		&i.NextAttemptAt,
		&i.LastAttemptAt,
		&i.DeliveredAt,
		&i.CreatedAt,
	)
	return i, err
}
