// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit_log.sql

package repository

import (
	"context"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

const createAuditLog = `-- name: CreateAuditLog :exec
INSERT INTO audit_log (tenant_id, action, entity_type, entity_id, actor_id, meta)
VALUES ($1, $2, $3, $4, $5, $6)
`

type CreateAuditLogParams struct {
	TenantID   uuid.UUID             `json:"tenant_id"`
	Action     string                `json:"action"`
	EntityType string                `json:"entity_type"`
	EntityID   uuid.NullUUID         `json:"entity_id"`
	ActorID    uuid.NullUUID         `json:"actor_id"`
	Meta       pqtype.NullRawMessage `json:"meta"`
}

func (q *Queries) CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) error {
	_, err := q.db.ExecContext(ctx, createAuditLog,
		arg.TenantID,
		arg.Action,
		arg.EntityType,
		arg.EntityID,
		arg.ActorID,
		arg.Meta,
	)
	return err
}
