// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: idempotency.sql

package repository

import (
	"context"
	"database/sql"
	"encoding/json"

	"github.com/google/uuid"
)

const cleanupExpiredIdempotencyKeys = `-- name: CleanupExpiredIdempotencyKeys :exec
DELETE FROM idempotency_keys WHERE expires_at < now()
`

func (q *Queries) CleanupExpiredIdempotencyKeys(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, cleanupExpiredIdempotencyKeys)
	return err
}

const getIdempotencyKey = `-- name: GetIdempotencyKey :one
SELECT tenant_id, idem_key, method, path, status_code, response_body, session_id, created_at, expires_at, request_hash FROM idempotency_keys
WHERE tenant_id = $1
  AND idem_key  = $2
  AND method    = $3
  AND path      = $4
  AND expires_at > now()
`

type GetIdempotencyKeyParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	IdemKey  string    `json:"idem_key"`
	Method   string    `json:"method"`
	Path     string    `json:"path"`
}

// Возвращает закэшированный response для (tenant, key, method, path) если
// он ещё не истёк. NULL → нужно обработать запрос обычным flow.
func (q *Queries) GetIdempotencyKey(ctx context.Context, arg GetIdempotencyKeyParams) (IdempotencyKey, error) {
	row := q.db.QueryRowContext(ctx, getIdempotencyKey,
		arg.TenantID,
		arg.IdemKey,
		arg.Method,
		arg.Path,
	)
	var i IdempotencyKey
	err := row.Scan(
		&i.TenantID,
		&i.IdemKey,
		&i.Method,
		&i.Path,
		&i.StatusCode,
		&i.ResponseBody,
		&i.SessionID,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.RequestHash,
	)
	return i, err
}

const putIdempotencyKey = `-- name: PutIdempotencyKey :exec
INSERT INTO idempotency_keys (
    tenant_id, idem_key, method, path, status_code, response_body, session_id, request_hash
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
)
ON CONFLICT (tenant_id, idem_key, method, path) DO NOTHING
`

type PutIdempotencyKeyParams struct {
	TenantID     uuid.UUID       `json:"tenant_id"`
	IdemKey      string          `json:"idem_key"`
	Method       string          `json:"method"`
	Path         string          `json:"path"`
	StatusCode   int32           `json:"status_code"`
	ResponseBody json.RawMessage `json:"response_body"`
	SessionID    uuid.NullUUID   `json:"session_id"`
	RequestHash  sql.NullString  `json:"request_hash"`
}

// Сохраняет результат обработки вместе с фингерпринтом тела запроса
// (request_hash) — он нужен, чтобы поймать переиспользование ключа с другим
// payload. ON CONFLICT DO NOTHING — если две параллельные транзакции дошли
// сюда, первая выигрывает; вторая запросом GetIdempotencyKey увидит её
// результат при ретрае.
func (q *Queries) PutIdempotencyKey(ctx context.Context, arg PutIdempotencyKeyParams) error {
	_, err := q.db.ExecContext(ctx, putIdempotencyKey,
		arg.TenantID,
		arg.IdemKey,
		arg.Method,
		arg.Path,
		arg.StatusCode,
		arg.ResponseBody,
		arg.SessionID,
		arg.RequestHash,
	)
	return err
}
