// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repository

import (
	"database/sql"
	"database/sql/driver"
	"encoding/json"
	"fmt"
	"time"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

type DocStatus string

const (
	DocStatusDraft           DocStatus = "draft"
	DocStatusPending         DocStatus = "pending"
	DocStatusPartiallySigned DocStatus = "partially_signed"
	DocStatusSigned          DocStatus = "signed"
	DocStatusRejected        DocStatus = "rejected"
)

func (e *DocStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = DocStatus(s)
	case string:
		*e = DocStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for DocStatus: %T", src)
	}
	return nil
}

type NullDocStatus struct {
	DocStatus DocStatus `json:"doc_status"`
	Valid     bool      `json:"valid"` // Valid is true if DocStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullDocStatus) Scan(value interface{}) error {
	if value == nil {
		ns.DocStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.DocStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullDocStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.DocStatus), nil
}

type OcspStatusType string

const (
	OcspStatusTypeGood    OcspStatusType = "good"
	OcspStatusTypeRevoked OcspStatusType = "revoked"
	OcspStatusTypeUnknown OcspStatusType = "unknown"
)

func (e *OcspStatusType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = OcspStatusType(s)
	case string:
		*e = OcspStatusType(s)
	default:
		return fmt.Errorf("unsupported scan type for OcspStatusType: %T", src)
	}
	return nil
}

type NullOcspStatusType struct {
	OcspStatusType OcspStatusType `json:"ocsp_status_type"`
	Valid          bool           `json:"valid"` // Valid is true if OcspStatusType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullOcspStatusType) Scan(value interface{}) error {
	if value == nil {
		ns.OcspStatusType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.OcspStatusType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullOcspStatusType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.OcspStatusType), nil
}

type TenantType string

const (
	TenantTypeIndividual  TenantType = "individual"
	TenantTypeLegalEntity TenantType = "legal_entity"
)

func (e *TenantType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TenantType(s)
	case string:
		*e = TenantType(s)
	default:
		return fmt.Errorf("unsupported scan type for TenantType: %T", src)
	}
	return nil
}

type NullTenantType struct {
	TenantType TenantType `json:"tenant_type"`
	Valid      bool       `json:"valid"` // Valid is true if TenantType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTenantType) Scan(value interface{}) error {
	if value == nil {
		ns.TenantType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TenantType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTenantType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TenantType), nil
}

type ApiKey struct {
	ID         uuid.UUID    `json:"id"`
	TenantID   uuid.UUID    `json:"tenant_id"`
	KeyHash    string       `json:"key_hash"`
	Label      string       `json:"label"`
	IsActive   bool         `json:"is_active"`
	LastUsedAt sql.NullTime `json:"last_used_at"`
	ExpiresAt  sql.NullTime `json:"expires_at"`
	CreatedAt  time.Time    `json:"created_at"`
}

type AuditLog struct {
	ID         uuid.UUID             `json:"id"`
	TenantID   uuid.UUID             `json:"tenant_id"`
	Action     string                `json:"action"`
	EntityType string                `json:"entity_type"`
	EntityID   uuid.NullUUID         `json:"entity_id"`
	ActorID    uuid.NullUUID         `json:"actor_id"`
	Meta       pqtype.NullRawMessage `json:"meta"`
	CreatedAt  time.Time             `json:"created_at"`
}

type AuthToken struct {
	ID        uuid.UUID     `json:"id"`
	UserID    uuid.NullUUID `json:"user_id"`
	TokenHash string        `json:"token_hash"`
	ExpiresAt time.Time     `json:"expires_at"`
	CreatedAt sql.NullTime  `json:"created_at"`
}

type Document struct {
	ID             uuid.UUID             `json:"id"`
	TenantID       uuid.UUID             `json:"tenant_id"`
	Title          sql.NullString        `json:"title"`
	S3KeyOriginal  string                `json:"s3_key_original"`
	S3KeyCurrent   string                `json:"s3_key_current"`
	CurrentVersion int32                 `json:"current_version"`
	Status         DocStatus             `json:"status"`
	Metadata       pqtype.NullRawMessage `json:"metadata"`
	CreatedAt      time.Time             `json:"created_at"`
	UpdatedAt      time.Time             `json:"updated_at"`
}

type DocumentVersion struct {
	ID         uuid.UUID `json:"id"`
	DocumentID uuid.UUID `json:"document_id"`
	TenantID   uuid.UUID `json:"tenant_id"`
	Version    int32     `json:"version"`
	S3Key      string    `json:"s3_key"`
	CreatedAt  time.Time `json:"created_at"`
}

type Signature struct {
	ID            uuid.UUID      `json:"id"`
	DocumentID    uuid.UUID      `json:"document_id"`
	TenantID      uuid.UUID      `json:"tenant_id"`
	VersionNumber int32          `json:"version_number"`
	SequenceNum   int32          `json:"sequence_num"`
	CmsB64        string         `json:"cms_b64"`
	Role          string         `json:"role"`
	SignerIin     sql.NullString `json:"signer_iin"`
	SignerName    string         `json:"signer_name"`
	SignerBin     sql.NullString `json:"signer_bin"`
	OrgName       sql.NullString `json:"org_name"`
	SignerType    string         `json:"signer_type"`
	Basis         sql.NullString `json:"basis"`
	CertSerial    string         `json:"cert_serial"`
	CertNotBefore time.Time      `json:"cert_not_before"`
	CertNotAfter  time.Time      `json:"cert_not_after"`
	CaName        string         `json:"ca_name"`
	OcspStatus    OcspStatusType `json:"ocsp_status"`
	OcspCheckedAt time.Time      `json:"ocsp_checked_at"`
	TspTime       sql.NullTime   `json:"tsp_time"`
	Sha256Hash    string         `json:"sha256_hash"`
	SignFormat    string         `json:"sign_format"`
	QrUrl         string         `json:"qr_url"`
	SignedAt      time.Time      `json:"signed_at"`
}

type Tenant struct {
	ID        uuid.UUID  `json:"id"`
	Name      string     `json:"name"`
	Type      TenantType `json:"type"`
	IsActive  bool       `json:"is_active"`
	CreatedAt time.Time  `json:"created_at"`
}

type User struct {
	ID           uuid.UUID     `json:"id"`
	Email        string        `json:"email"`
	PasswordHash string        `json:"password_hash"`
	Name         string        `json:"name"`
	TenantID     uuid.NullUUID `json:"tenant_id"`
	Role         string        `json:"role"`
	IsActive     sql.NullBool  `json:"is_active"`
	CreatedAt    sql.NullTime  `json:"created_at"`
	LastLoginAt  sql.NullTime  `json:"last_login_at"`
}

type Webhook struct {
	ID        uuid.UUID `json:"id"`
	TenantID  uuid.UUID `json:"tenant_id"`
	Url       string    `json:"url"`
	Events    []string  `json:"events"`
	Secret    string    `json:"secret"`
	IsActive  bool      `json:"is_active"`
	CreatedAt time.Time `json:"created_at"`
}

type WebhookDelivery struct {
	ID           uuid.UUID       `json:"id"`
	WebhookID    uuid.UUID       `json:"webhook_id"`
	Event        string          `json:"event"`
	Payload      json.RawMessage `json:"payload"`
	Attempt      int32           `json:"attempt"`
	Status       string          `json:"status"`
	ResponseCode sql.NullInt32   `json:"response_code"`
	ErrorMsg     sql.NullString  `json:"error_msg"`
	ScheduledAt  time.Time       `json:"scheduled_at"`
	DeliveredAt  sql.NullTime    `json:"delivered_at"`
}
