// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repository

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

type Querier interface {
	CancelApplication(ctx context.Context, arg CancelApplicationParams) (Application, error)
	CleanupExpiredIdempotencyKeys(ctx context.Context) error
	CountSigningSessionDocumentsForRegistry(ctx context.Context, arg CountSigningSessionDocumentsForRegistryParams) (int64, error)
	CreateAPIKey(ctx context.Context, arg CreateAPIKeyParams) (ApiKey, error)
	CreateApplication(ctx context.Context, arg CreateApplicationParams) (Application, error)
	CreateApplicationDocument(ctx context.Context, arg CreateApplicationDocumentParams) (ApplicationDocument, error)
	CreateApplicationWebhook(ctx context.Context, arg CreateApplicationWebhookParams) (ApplicationWebhook, error)
	CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) error
	CreateAuthToken(ctx context.Context, arg CreateAuthTokenParams) (AuthToken, error)
	CreateDocument(ctx context.Context, arg CreateDocumentParams) (Document, error)
	CreateDocumentVersion(ctx context.Context, arg CreateDocumentVersionParams) (DocumentVersion, error)
	CreateSignature(ctx context.Context, arg CreateSignatureParams) (Signature, error)
	CreateSignatureWithID(ctx context.Context, arg CreateSignatureWithIDParams) (Signature, error)
	CreateSigningSession(ctx context.Context, arg CreateSigningSessionParams) (SigningSession, error)
	CreateSigningSessionDocument(ctx context.Context, arg CreateSigningSessionDocumentParams) (SigningSessionDocument, error)
	// client-mode: хэш и метаданные пришли из /sign/initiate; статус сразу 'ready',
	// фетчер для подсчёта хэша не нужен (PDF всё равно кэшируется при первом обращении).
	CreateSigningSessionDocumentWithHash(ctx context.Context, arg CreateSigningSessionDocumentWithHashParams) (SigningSessionDocument, error)
	CreateTenant(ctx context.Context, arg CreateTenantParams) (Tenant, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateWebhook(ctx context.Context, arg CreateWebhookParams) (Webhook, error)
	CreateWebhookDelivery(ctx context.Context, arg CreateWebhookDeliveryParams) (WebhookDelivery, error)
	DeactivateAPIKey(ctx context.Context, arg DeactivateAPIKeyParams) error
	DeactivateWebhook(ctx context.Context, arg DeactivateWebhookParams) error
	DeleteAuthToken(ctx context.Context, tokenHash string) error
	DeleteExpiredTokens(ctx context.Context) error
	DeleteUser(ctx context.Context, id uuid.UUID) error
	FindPreviousVersions(ctx context.Context, arg FindPreviousVersionsParams) ([]ApplicationDocument, error)
	GetAPIKeyByHash(ctx context.Context, keyHash string) (ApiKey, error)
	GetApplicationByExternalID(ctx context.Context, arg GetApplicationByExternalIDParams) (Application, error)
	GetApplicationByID(ctx context.Context, arg GetApplicationByIDParams) (Application, error)
	GetApplicationDocumentByID(ctx context.Context, id uuid.UUID) (ApplicationDocument, error)
	GetAuthTokenByHash(ctx context.Context, tokenHash string) (AuthToken, error)
	GetDocument(ctx context.Context, arg GetDocumentParams) (Document, error)
	GetDocumentByCurrentSHA256(ctx context.Context, arg GetDocumentByCurrentSHA256Params) (Document, error)
	GetDocumentBySHA256(ctx context.Context, arg GetDocumentBySHA256Params) (Document, error)
	GetDocumentCallbackURL(ctx context.Context, id uuid.UUID) (sql.NullString, error)
	GetExpiredSessions(ctx context.Context) ([]SigningSession, error)
	// Возвращает закэшированный response для (tenant, key, method, path) если
	// он ещё не истёк. NULL → нужно обработать запрос обычным flow.
	GetIdempotencyKey(ctx context.Context, arg GetIdempotencyKeyParams) (IdempotencyKey, error)
	GetPendingFetchDocuments(ctx context.Context, limit int32) ([]ApplicationDocument, error)
	GetPendingFetchSessionDocuments(ctx context.Context) ([]SigningSessionDocument, error)
	GetPendingWebhooks(ctx context.Context) ([]ApplicationWebhook, error)
	GetSignature(ctx context.Context, arg GetSignatureParams) (Signature, error)
	GetSignatureByIDPublic(ctx context.Context, id uuid.UUID) (Signature, error)
	GetSignaturesByDocument(ctx context.Context, arg GetSignaturesByDocumentParams) ([]Signature, error)
	GetSigningSession(ctx context.Context, arg GetSigningSessionParams) (SigningSession, error)
	GetSigningSessionByID(ctx context.Context, id uuid.UUID) (SigningSession, error)
	GetSigningSessionDocument(ctx context.Context, id uuid.UUID) (SigningSessionDocument, error)
	GetTenant(ctx context.Context, id uuid.UUID) (Tenant, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	GetWebhookByID(ctx context.Context, id uuid.UUID) (Webhook, error)
	GetWebhookDeliveryByID(ctx context.Context, id uuid.UUID) (WebhookDelivery, error)
	GetWebhooksByTenantAndEvent(ctx context.Context, arg GetWebhooksByTenantAndEventParams) ([]Webhook, error)
	IncrementSessionDocumentUploadAttempts(ctx context.Context, arg IncrementSessionDocumentUploadAttemptsParams) (SigningSessionDocument, error)
	IncrementUploadAttempts(ctx context.Context, arg IncrementUploadAttemptsParams) (ApplicationDocument, error)
	ListAPIKeysByTenant(ctx context.Context, tenantID uuid.UUID) ([]ApiKey, error)
	ListActiveApplicationDocuments(ctx context.Context, arg ListActiveApplicationDocumentsParams) ([]ApplicationDocument, error)
	ListApplicationDocuments(ctx context.Context, applicationID uuid.UUID) ([]ApplicationDocument, error)
	// Воркер берёт пачку документов, готовых к проверке. SKIP LOCKED — для безопасной
	// работы нескольких инстансов воркера одновременно.
	ListDocumentsForVerification(ctx context.Context, limit int32) ([]SigningSessionDocument, error)
	ListPendingWebhookDeliveries(ctx context.Context, limit int32) ([]WebhookDelivery, error)
	ListReadySessionDocuments(ctx context.Context, sessionID uuid.UUID) ([]SigningSessionDocument, error)
	// Порядок гарантируется: сначала по client_index (если есть), затем по
	// created_at (для legacy-сессий и tie-breaker). Lovable сопоставляет
	// response.documents с request.documents по индексу.
	ListSessionDocuments(ctx context.Context, sessionID uuid.UUID) ([]SigningSessionDocument, error)
	// Реестр подписаний (admin-only): по документам, не по сессиям — оператор
	// должен видеть каждый документ отдельно. tenant_id/status — nullable
	// фильтры, NULL = без фильтра.
	ListSigningSessionDocumentsForRegistry(ctx context.Context, arg ListSigningSessionDocumentsForRegistryParams) ([]ListSigningSessionDocumentsForRegistryRow, error)
	ListTenantsWithKeyCount(ctx context.Context) ([]ListTenantsWithKeyCountRow, error)
	ListUsers(ctx context.Context) ([]User, error)
	ListWebhooksByTenant(ctx context.Context, tenantID uuid.UUID) ([]Webhook, error)
	MarkApplicationDocumentUploaded(ctx context.Context, id uuid.UUID) (ApplicationDocument, error)
	// client-mode + sanity-check провалился: реально посчитанный SHA не совпал
	// с клиентским hash. Документ окончательно отбракован.
	MarkSessionDocumentTampered(ctx context.Context, arg MarkSessionDocumentTamperedParams) (SigningSessionDocument, error)
	MarkSessionDocumentUploaded(ctx context.Context, id uuid.UUID) (SigningSessionDocument, error)
	// Вызывается из /sign/complete после успешной sync-сверки messageDigest.
	// Первая проверка асинхронным воркером откладывается на InitialDelay секунд.
	MarkSessionDocumentVerificationPending(ctx context.Context, arg MarkSessionDocumentVerificationPendingParams) error
	// Сохраняет результат обработки вместе с фингерпринтом тела запроса
	// (request_hash) — он нужен, чтобы поймать переиспользование ключа с другим
	// payload. ON CONFLICT DO NOTHING — если две параллельные транзакции дошли
	// сюда, первая выигрывает; вторая запросом GetIdempotencyKey увидит её
	// результат при ретрае.
	PutIdempotencyKey(ctx context.Context, arg PutIdempotencyKeyParams) error
	// Worst-of агрегат: любой не-'verified' документ перетягивает статус сессии.
	// Приоритет: mismatch > unavailable > pending > verified. Сессии без verification-
	// атрибутов у документов не трогаем.
	RecalcSessionVerification(ctx context.Context, id uuid.UUID) error
	ResetSessionDocumentForRetry(ctx context.Context, arg ResetSessionDocumentForRetryParams) (SigningSessionDocument, error)
	SupersedeApplicationDocument(ctx context.Context, arg SupersedeApplicationDocumentParams) (ApplicationDocument, error)
	UpdateAPIKeyLastUsed(ctx context.Context, id uuid.UUID) error
	UpdateApplicationDocumentAfterFetch(ctx context.Context, arg UpdateApplicationDocumentAfterFetchParams) (ApplicationDocument, error)
	UpdateApplicationDocumentStatus(ctx context.Context, arg UpdateApplicationDocumentStatusParams) (ApplicationDocument, error)
	UpdateApplicationDocumentTargetURL(ctx context.Context, arg UpdateApplicationDocumentTargetURLParams) (ApplicationDocument, error)
	UpdateApplicationStatus(ctx context.Context, arg UpdateApplicationStatusParams) (Application, error)
	UpdateDocumentStatus(ctx context.Context, arg UpdateDocumentStatusParams) (Document, error)
	// Финальная или промежуточная запись результата проверки. attempts инкрементируется
	// атомарно. error/source_meta_hash могут быть NULL.
	UpdateDocumentVerification(ctx context.Context, arg UpdateDocumentVerificationParams) error
	UpdateDocumentVersion(ctx context.Context, arg UpdateDocumentVersionParams) (Document, error)
	// legacy: пишет content_hash из посчитанного фетчером значения.
	UpdateSessionDocumentAfterFetch(ctx context.Context, arg UpdateSessionDocumentAfterFetchParams) (SigningSessionDocument, error)
	// client-mode: hash уже записан, фетчер только кэширует PDF.
	UpdateSessionDocumentAfterFetchKeepHash(ctx context.Context, arg UpdateSessionDocumentAfterFetchKeepHashParams) (SigningSessionDocument, error)
	UpdateSessionDocumentAfterSign(ctx context.Context, arg UpdateSessionDocumentAfterSignParams) (SigningSessionDocument, error)
	// Персистит ncanode.VerifyResult + реальный verify QR-URL. Non-fatal при
	// ошибке (вызывающий код логирует и продолжает — PDF уже собран корректно).
	UpdateSessionDocumentSignerInfo(ctx context.Context, arg UpdateSessionDocumentSignerInfoParams) (SigningSessionDocument, error)
	UpdateSessionDocumentStatus(ctx context.Context, arg UpdateSessionDocumentStatusParams) (SigningSessionDocument, error)
	UpdateSessionDocumentTargetURL(ctx context.Context, arg UpdateSessionDocumentTargetURLParams) (SigningSessionDocument, error)
	UpdateSigningSessionStatus(ctx context.Context, arg UpdateSigningSessionStatusParams) (SigningSession, error)
	UpdateUserLastLogin(ctx context.Context, id uuid.UUID) error
	UpdateUserRole(ctx context.Context, arg UpdateUserRoleParams) (User, error)
	UpdateWebhookDeliveryFailed(ctx context.Context, arg UpdateWebhookDeliveryFailedParams) error
	UpdateWebhookDeliverySuccess(ctx context.Context, id uuid.UUID) error
	UpdateWebhookStatus(ctx context.Context, arg UpdateWebhookStatusParams) (ApplicationWebhook, error)
}

var _ Querier = (*Queries)(nil)
