// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repository

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

type Querier interface {
	CreateAPIKey(ctx context.Context, arg CreateAPIKeyParams) (ApiKey, error)
	CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) error
	CreateAuthToken(ctx context.Context, arg CreateAuthTokenParams) (AuthToken, error)
	CreateDocument(ctx context.Context, arg CreateDocumentParams) (Document, error)
	CreateDocumentVersion(ctx context.Context, arg CreateDocumentVersionParams) (DocumentVersion, error)
	CreateSignature(ctx context.Context, arg CreateSignatureParams) (Signature, error)
	CreateSignatureWithID(ctx context.Context, arg CreateSignatureWithIDParams) (Signature, error)
	CreateTenant(ctx context.Context, arg CreateTenantParams) (Tenant, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateWebhookDelivery(ctx context.Context, arg CreateWebhookDeliveryParams) (WebhookDelivery, error)
	DeactivateAPIKey(ctx context.Context, arg DeactivateAPIKeyParams) error
	DeleteAuthToken(ctx context.Context, tokenHash string) error
	DeleteExpiredTokens(ctx context.Context) error
	DeleteUser(ctx context.Context, id uuid.UUID) error
	GetAPIKeyByHash(ctx context.Context, keyHash string) (ApiKey, error)
	GetAuthTokenByHash(ctx context.Context, tokenHash string) (AuthToken, error)
	GetDocument(ctx context.Context, arg GetDocumentParams) (Document, error)
	GetDocumentByCurrentSHA256(ctx context.Context, arg GetDocumentByCurrentSHA256Params) (Document, error)
	GetDocumentBySHA256(ctx context.Context, arg GetDocumentBySHA256Params) (Document, error)
	GetDocumentCallbackURL(ctx context.Context, id uuid.UUID) (sql.NullString, error)
	GetSignature(ctx context.Context, arg GetSignatureParams) (Signature, error)
	GetSignatureByIDPublic(ctx context.Context, id uuid.UUID) (Signature, error)
	GetSignaturesByDocument(ctx context.Context, arg GetSignaturesByDocumentParams) ([]Signature, error)
	GetTenant(ctx context.Context, id uuid.UUID) (Tenant, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	GetWebhookByID(ctx context.Context, id uuid.UUID) (Webhook, error)
	GetWebhookDeliveryByID(ctx context.Context, id uuid.UUID) (WebhookDelivery, error)
	GetWebhooksByTenantAndEvent(ctx context.Context, arg GetWebhooksByTenantAndEventParams) ([]Webhook, error)
	ListAPIKeysByTenant(ctx context.Context, tenantID uuid.UUID) ([]ApiKey, error)
	ListTenantsWithKeyCount(ctx context.Context) ([]ListTenantsWithKeyCountRow, error)
	ListUsers(ctx context.Context) ([]User, error)
	UpdateAPIKeyLastUsed(ctx context.Context, id uuid.UUID) error
	UpdateDocumentStatus(ctx context.Context, arg UpdateDocumentStatusParams) (Document, error)
	UpdateDocumentVersion(ctx context.Context, arg UpdateDocumentVersionParams) (Document, error)
	UpdateUserLastLogin(ctx context.Context, id uuid.UUID) error
	UpdateUserRole(ctx context.Context, arg UpdateUserRoleParams) (User, error)
	UpdateWebhookDeliveryFailed(ctx context.Context, arg UpdateWebhookDeliveryFailedParams) error
	UpdateWebhookDeliverySuccess(ctx context.Context, id uuid.UUID) error
}

var _ Querier = (*Queries)(nil)
