// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: signing_sessions.sql

package repository

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const countSigningSessionDocumentsForRegistry = `-- name: CountSigningSessionDocumentsForRegistry :one
SELECT count(*) FROM signing_session_documents ssd
JOIN signing_sessions ss ON ss.id = ssd.session_id
WHERE ($1::uuid IS NULL OR ss.tenant_id = $1::uuid)
  AND ($2::text IS NULL OR ssd.status = $2::text)
`

type CountSigningSessionDocumentsForRegistryParams struct {
	TenantID  uuid.NullUUID  `json:"tenant_id"`
	DocStatus sql.NullString `json:"doc_status"`
}

func (q *Queries) CountSigningSessionDocumentsForRegistry(ctx context.Context, arg CountSigningSessionDocumentsForRegistryParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countSigningSessionDocumentsForRegistry, arg.TenantID, arg.DocStatus)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createSigningSession = `-- name: CreateSigningSession :one
INSERT INTO signing_sessions (
    tenant_id, application_id, signer_role, callback_url, callback_secret, status, expires_at
) VALUES (
    $1, $2, $3, $4, $5, 'pending', COALESCE($6, now() + INTERVAL '2 hours')
)
RETURNING id, tenant_id, application_id, signer_role, callback_url, callback_secret, status, expires_at, created_at, updated_at, verification_status
`

type CreateSigningSessionParams struct {
	TenantID       uuid.UUID      `json:"tenant_id"`
	ApplicationID  sql.NullString `json:"application_id"`
	SignerRole     string         `json:"signer_role"`
	CallbackUrl    sql.NullString `json:"callback_url"`
	CallbackSecret sql.NullString `json:"callback_secret"`
	Column6        interface{}    `json:"column_6"`
}

func (q *Queries) CreateSigningSession(ctx context.Context, arg CreateSigningSessionParams) (SigningSession, error) {
	row := q.db.QueryRowContext(ctx, createSigningSession,
		arg.TenantID,
		arg.ApplicationID,
		arg.SignerRole,
		arg.CallbackUrl,
		arg.CallbackSecret,
		arg.Column6,
	)
	var i SigningSession
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ApplicationID,
		&i.SignerRole,
		&i.CallbackUrl,
		&i.CallbackSecret,
		&i.Status,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.VerificationStatus,
	)
	return i, err
}

const createSigningSessionDocument = `-- name: CreateSigningSessionDocument :one
INSERT INTO signing_session_documents (
    session_id, document_name, source_url, target_url, target_s3_key,
    content_hash, status, client_index, client_ref
) VALUES (
    $1, $2, $3, $4, $5, '', 'pending', $6, $7
)
RETURNING id, session_id, document_name, source_url, target_url, target_s3_key, content_hash, cached_s3_key, signed_s3_key, cms_s3_key, status, last_error, upload_attempts, signed_at, uploaded_at, created_at, hash_source, source_s3_bucket, source_s3_key, source_content_type, source_size_bytes, source_meta_hash, verification_status, verification_checked_at, verification_error, verification_attempts, verification_next_at, client_index, client_ref, signer_iin, signer_name, signer_bin, org_name, signer_type, basis, cert_serial, cert_not_before, cert_not_after, ca_name, ocsp_status, tsp_time, sign_format, qr_url
`

type CreateSigningSessionDocumentParams struct {
	SessionID    uuid.UUID      `json:"session_id"`
	DocumentName string         `json:"document_name"`
	SourceUrl    string         `json:"source_url"`
	TargetUrl    sql.NullString `json:"target_url"`
	TargetS3Key  sql.NullString `json:"target_s3_key"`
	ClientIndex  sql.NullInt32  `json:"client_index"`
	ClientRef    sql.NullString `json:"client_ref"`
}

func (q *Queries) CreateSigningSessionDocument(ctx context.Context, arg CreateSigningSessionDocumentParams) (SigningSessionDocument, error) {
	row := q.db.QueryRowContext(ctx, createSigningSessionDocument,
		arg.SessionID,
		arg.DocumentName,
		arg.SourceUrl,
		arg.TargetUrl,
		arg.TargetS3Key,
		arg.ClientIndex,
		arg.ClientRef,
	)
	var i SigningSessionDocument
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.DocumentName,
		&i.SourceUrl,
		&i.TargetUrl,
		&i.TargetS3Key,
		&i.ContentHash,
		&i.CachedS3Key,
		&i.SignedS3Key,
		&i.CmsS3Key,
		&i.Status,
		&i.LastError,
		&i.UploadAttempts,
		&i.SignedAt,
		&i.UploadedAt,
		&i.CreatedAt,
		&i.HashSource,
		&i.SourceS3Bucket,
		&i.SourceS3Key,
		&i.SourceContentType,
		&i.SourceSizeBytes,
		&i.SourceMetaHash,
		&i.VerificationStatus,
		&i.VerificationCheckedAt,
		&i.VerificationError,
		&i.VerificationAttempts,
		&i.VerificationNextAt,
		&i.ClientIndex,
		&i.ClientRef,
		&i.SignerIin,
		&i.SignerName,
		&i.SignerBin,
		&i.OrgName,
		&i.SignerType,
		&i.Basis,
		&i.CertSerial,
		&i.CertNotBefore,
		&i.CertNotAfter,
		&i.CaName,
		&i.OcspStatus,
		&i.TspTime,
		&i.SignFormat,
		&i.QrUrl,
	)
	return i, err
}

const createSigningSessionDocumentWithHash = `-- name: CreateSigningSessionDocumentWithHash :one
INSERT INTO signing_session_documents (
    session_id, document_name, source_url, target_url, target_s3_key,
    content_hash, hash_source,
    source_s3_bucket, source_s3_key, source_content_type, source_size_bytes,
    status, client_index, client_ref
) VALUES (
    $1, $2, $3, $4, $5,
    $6, 'client',
    $7, $8, $9, $10,
    'ready', $11, $12
)
RETURNING id, session_id, document_name, source_url, target_url, target_s3_key, content_hash, cached_s3_key, signed_s3_key, cms_s3_key, status, last_error, upload_attempts, signed_at, uploaded_at, created_at, hash_source, source_s3_bucket, source_s3_key, source_content_type, source_size_bytes, source_meta_hash, verification_status, verification_checked_at, verification_error, verification_attempts, verification_next_at, client_index, client_ref, signer_iin, signer_name, signer_bin, org_name, signer_type, basis, cert_serial, cert_not_before, cert_not_after, ca_name, ocsp_status, tsp_time, sign_format, qr_url
`

type CreateSigningSessionDocumentWithHashParams struct {
	SessionID         uuid.UUID      `json:"session_id"`
	DocumentName      string         `json:"document_name"`
	SourceUrl         string         `json:"source_url"`
	TargetUrl         sql.NullString `json:"target_url"`
	TargetS3Key       sql.NullString `json:"target_s3_key"`
	ContentHash       sql.NullString `json:"content_hash"`
	SourceS3Bucket    sql.NullString `json:"source_s3_bucket"`
	SourceS3Key       sql.NullString `json:"source_s3_key"`
	SourceContentType sql.NullString `json:"source_content_type"`
	SourceSizeBytes   sql.NullInt64  `json:"source_size_bytes"`
	ClientIndex       sql.NullInt32  `json:"client_index"`
	ClientRef         sql.NullString `json:"client_ref"`
}

// client-mode: хэш и метаданные пришли из /sign/initiate; статус сразу 'ready',
// фетчер для подсчёта хэша не нужен (PDF всё равно кэшируется при первом обращении).
func (q *Queries) CreateSigningSessionDocumentWithHash(ctx context.Context, arg CreateSigningSessionDocumentWithHashParams) (SigningSessionDocument, error) {
	row := q.db.QueryRowContext(ctx, createSigningSessionDocumentWithHash,
		arg.SessionID,
		arg.DocumentName,
		arg.SourceUrl,
		arg.TargetUrl,
		arg.TargetS3Key,
		arg.ContentHash,
		arg.SourceS3Bucket,
		arg.SourceS3Key,
		arg.SourceContentType,
		arg.SourceSizeBytes,
		arg.ClientIndex,
		arg.ClientRef,
	)
	var i SigningSessionDocument
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.DocumentName,
		&i.SourceUrl,
		&i.TargetUrl,
		&i.TargetS3Key,
		&i.ContentHash,
		&i.CachedS3Key,
		&i.SignedS3Key,
		&i.CmsS3Key,
		&i.Status,
		&i.LastError,
		&i.UploadAttempts,
		&i.SignedAt,
		&i.UploadedAt,
		&i.CreatedAt,
		&i.HashSource,
		&i.SourceS3Bucket,
		&i.SourceS3Key,
		&i.SourceContentType,
		&i.SourceSizeBytes,
		&i.SourceMetaHash,
		&i.VerificationStatus,
		&i.VerificationCheckedAt,
		&i.VerificationError,
		&i.VerificationAttempts,
		&i.VerificationNextAt,
		&i.ClientIndex,
		&i.ClientRef,
		&i.SignerIin,
		&i.SignerName,
		&i.SignerBin,
		&i.OrgName,
		&i.SignerType,
		&i.Basis,
		&i.CertSerial,
		&i.CertNotBefore,
		&i.CertNotAfter,
		&i.CaName,
		&i.OcspStatus,
		&i.TspTime,
		&i.SignFormat,
		&i.QrUrl,
	)
	return i, err
}

const getExpiredSessions = `-- name: GetExpiredSessions :many
SELECT id, tenant_id, application_id, signer_role, callback_url, callback_secret, status, expires_at, created_at, updated_at, verification_status FROM signing_sessions
WHERE expires_at < now()
  AND status NOT IN ('completed', 'failed', 'expired')
ORDER BY expires_at
LIMIT 100
`

func (q *Queries) GetExpiredSessions(ctx context.Context) ([]SigningSession, error) {
	rows, err := q.db.QueryContext(ctx, getExpiredSessions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SigningSession
	for rows.Next() {
		var i SigningSession
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ApplicationID,
			&i.SignerRole,
			&i.CallbackUrl,
			&i.CallbackSecret,
			&i.Status,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.VerificationStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPendingFetchSessionDocuments = `-- name: GetPendingFetchSessionDocuments :many
SELECT ssd.id, ssd.session_id, ssd.document_name, ssd.source_url, ssd.target_url, ssd.target_s3_key, ssd.content_hash, ssd.cached_s3_key, ssd.signed_s3_key, ssd.cms_s3_key, ssd.status, ssd.last_error, ssd.upload_attempts, ssd.signed_at, ssd.uploaded_at, ssd.created_at, ssd.hash_source, ssd.source_s3_bucket, ssd.source_s3_key, ssd.source_content_type, ssd.source_size_bytes, ssd.source_meta_hash, ssd.verification_status, ssd.verification_checked_at, ssd.verification_error, ssd.verification_attempts, ssd.verification_next_at, ssd.client_index, ssd.client_ref, ssd.signer_iin, ssd.signer_name, ssd.signer_bin, ssd.org_name, ssd.signer_type, ssd.basis, ssd.cert_serial, ssd.cert_not_before, ssd.cert_not_after, ssd.ca_name, ssd.ocsp_status, ssd.tsp_time, ssd.sign_format, ssd.qr_url FROM signing_session_documents ssd
JOIN signing_sessions ss ON ss.id = ssd.session_id
WHERE ssd.status = 'pending'
  AND ss.status NOT IN ('expired', 'failed', 'completed')
  AND ss.expires_at > now()
ORDER BY ssd.created_at
LIMIT 20
`

func (q *Queries) GetPendingFetchSessionDocuments(ctx context.Context) ([]SigningSessionDocument, error) {
	rows, err := q.db.QueryContext(ctx, getPendingFetchSessionDocuments)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SigningSessionDocument
	for rows.Next() {
		var i SigningSessionDocument
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.DocumentName,
			&i.SourceUrl,
			&i.TargetUrl,
			&i.TargetS3Key,
			&i.ContentHash,
			&i.CachedS3Key,
			&i.SignedS3Key,
			&i.CmsS3Key,
			&i.Status,
			&i.LastError,
			&i.UploadAttempts,
			&i.SignedAt,
			&i.UploadedAt,
			&i.CreatedAt,
			&i.HashSource,
			&i.SourceS3Bucket,
			&i.SourceS3Key,
			&i.SourceContentType,
			&i.SourceSizeBytes,
			&i.SourceMetaHash,
			&i.VerificationStatus,
			&i.VerificationCheckedAt,
			&i.VerificationError,
			&i.VerificationAttempts,
			&i.VerificationNextAt,
			&i.ClientIndex,
			&i.ClientRef,
			&i.SignerIin,
			&i.SignerName,
			&i.SignerBin,
			&i.OrgName,
			&i.SignerType,
			&i.Basis,
			&i.CertSerial,
			&i.CertNotBefore,
			&i.CertNotAfter,
			&i.CaName,
			&i.OcspStatus,
			&i.TspTime,
			&i.SignFormat,
			&i.QrUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSigningSession = `-- name: GetSigningSession :one
SELECT id, tenant_id, application_id, signer_role, callback_url, callback_secret, status, expires_at, created_at, updated_at, verification_status FROM signing_sessions
WHERE id = $1 AND tenant_id = $2
`

type GetSigningSessionParams struct {
	ID       uuid.UUID `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

func (q *Queries) GetSigningSession(ctx context.Context, arg GetSigningSessionParams) (SigningSession, error) {
	row := q.db.QueryRowContext(ctx, getSigningSession, arg.ID, arg.TenantID)
	var i SigningSession
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ApplicationID,
		&i.SignerRole,
		&i.CallbackUrl,
		&i.CallbackSecret,
		&i.Status,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.VerificationStatus,
	)
	return i, err
}

const getSigningSessionByID = `-- name: GetSigningSessionByID :one
SELECT id, tenant_id, application_id, signer_role, callback_url, callback_secret, status, expires_at, created_at, updated_at, verification_status FROM signing_sessions
WHERE id = $1
`

func (q *Queries) GetSigningSessionByID(ctx context.Context, id uuid.UUID) (SigningSession, error) {
	row := q.db.QueryRowContext(ctx, getSigningSessionByID, id)
	var i SigningSession
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ApplicationID,
		&i.SignerRole,
		&i.CallbackUrl,
		&i.CallbackSecret,
		&i.Status,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.VerificationStatus,
	)
	return i, err
}

const getSigningSessionDocument = `-- name: GetSigningSessionDocument :one
SELECT id, session_id, document_name, source_url, target_url, target_s3_key, content_hash, cached_s3_key, signed_s3_key, cms_s3_key, status, last_error, upload_attempts, signed_at, uploaded_at, created_at, hash_source, source_s3_bucket, source_s3_key, source_content_type, source_size_bytes, source_meta_hash, verification_status, verification_checked_at, verification_error, verification_attempts, verification_next_at, client_index, client_ref, signer_iin, signer_name, signer_bin, org_name, signer_type, basis, cert_serial, cert_not_before, cert_not_after, ca_name, ocsp_status, tsp_time, sign_format, qr_url FROM signing_session_documents
WHERE id = $1
`

func (q *Queries) GetSigningSessionDocument(ctx context.Context, id uuid.UUID) (SigningSessionDocument, error) {
	row := q.db.QueryRowContext(ctx, getSigningSessionDocument, id)
	var i SigningSessionDocument
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.DocumentName,
		&i.SourceUrl,
		&i.TargetUrl,
		&i.TargetS3Key,
		&i.ContentHash,
		&i.CachedS3Key,
		&i.SignedS3Key,
		&i.CmsS3Key,
		&i.Status,
		&i.LastError,
		&i.UploadAttempts,
		&i.SignedAt,
		&i.UploadedAt,
		&i.CreatedAt,
		&i.HashSource,
		&i.SourceS3Bucket,
		&i.SourceS3Key,
		&i.SourceContentType,
		&i.SourceSizeBytes,
		&i.SourceMetaHash,
		&i.VerificationStatus,
		&i.VerificationCheckedAt,
		&i.VerificationError,
		&i.VerificationAttempts,
		&i.VerificationNextAt,
		&i.ClientIndex,
		&i.ClientRef,
		&i.SignerIin,
		&i.SignerName,
		&i.SignerBin,
		&i.OrgName,
		&i.SignerType,
		&i.Basis,
		&i.CertSerial,
		&i.CertNotBefore,
		&i.CertNotAfter,
		&i.CaName,
		&i.OcspStatus,
		&i.TspTime,
		&i.SignFormat,
		&i.QrUrl,
	)
	return i, err
}

const incrementSessionDocumentUploadAttempts = `-- name: IncrementSessionDocumentUploadAttempts :one
UPDATE signing_session_documents
SET upload_attempts = upload_attempts + 1, last_error = $2
WHERE id = $1
RETURNING id, session_id, document_name, source_url, target_url, target_s3_key, content_hash, cached_s3_key, signed_s3_key, cms_s3_key, status, last_error, upload_attempts, signed_at, uploaded_at, created_at, hash_source, source_s3_bucket, source_s3_key, source_content_type, source_size_bytes, source_meta_hash, verification_status, verification_checked_at, verification_error, verification_attempts, verification_next_at, client_index, client_ref, signer_iin, signer_name, signer_bin, org_name, signer_type, basis, cert_serial, cert_not_before, cert_not_after, ca_name, ocsp_status, tsp_time, sign_format, qr_url
`

type IncrementSessionDocumentUploadAttemptsParams struct {
	ID        uuid.UUID      `json:"id"`
	LastError sql.NullString `json:"last_error"`
}

func (q *Queries) IncrementSessionDocumentUploadAttempts(ctx context.Context, arg IncrementSessionDocumentUploadAttemptsParams) (SigningSessionDocument, error) {
	row := q.db.QueryRowContext(ctx, incrementSessionDocumentUploadAttempts, arg.ID, arg.LastError)
	var i SigningSessionDocument
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.DocumentName,
		&i.SourceUrl,
		&i.TargetUrl,
		&i.TargetS3Key,
		&i.ContentHash,
		&i.CachedS3Key,
		&i.SignedS3Key,
		&i.CmsS3Key,
		&i.Status,
		&i.LastError,
		&i.UploadAttempts,
		&i.SignedAt,
		&i.UploadedAt,
		&i.CreatedAt,
		&i.HashSource,
		&i.SourceS3Bucket,
		&i.SourceS3Key,
		&i.SourceContentType,
		&i.SourceSizeBytes,
		&i.SourceMetaHash,
		&i.VerificationStatus,
		&i.VerificationCheckedAt,
		&i.VerificationError,
		&i.VerificationAttempts,
		&i.VerificationNextAt,
		&i.ClientIndex,
		&i.ClientRef,
		&i.SignerIin,
		&i.SignerName,
		&i.SignerBin,
		&i.OrgName,
		&i.SignerType,
		&i.Basis,
		&i.CertSerial,
		&i.CertNotBefore,
		&i.CertNotAfter,
		&i.CaName,
		&i.OcspStatus,
		&i.TspTime,
		&i.SignFormat,
		&i.QrUrl,
	)
	return i, err
}

const listDocumentsForVerification = `-- name: ListDocumentsForVerification :many
SELECT id, session_id, document_name, source_url, target_url, target_s3_key, content_hash, cached_s3_key, signed_s3_key, cms_s3_key, status, last_error, upload_attempts, signed_at, uploaded_at, created_at, hash_source, source_s3_bucket, source_s3_key, source_content_type, source_size_bytes, source_meta_hash, verification_status, verification_checked_at, verification_error, verification_attempts, verification_next_at, client_index, client_ref, signer_iin, signer_name, signer_bin, org_name, signer_type, basis, cert_serial, cert_not_before, cert_not_after, ca_name, ocsp_status, tsp_time, sign_format, qr_url FROM signing_session_documents
WHERE verification_status IN ('pending', 'retrying')
  AND verification_next_at <= now()
ORDER BY verification_next_at
LIMIT $1
FOR UPDATE SKIP LOCKED
`

// Воркер берёт пачку документов, готовых к проверке. SKIP LOCKED — для безопасной
// работы нескольких инстансов воркера одновременно.
func (q *Queries) ListDocumentsForVerification(ctx context.Context, limit int32) ([]SigningSessionDocument, error) {
	rows, err := q.db.QueryContext(ctx, listDocumentsForVerification, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SigningSessionDocument
	for rows.Next() {
		var i SigningSessionDocument
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.DocumentName,
			&i.SourceUrl,
			&i.TargetUrl,
			&i.TargetS3Key,
			&i.ContentHash,
			&i.CachedS3Key,
			&i.SignedS3Key,
			&i.CmsS3Key,
			&i.Status,
			&i.LastError,
			&i.UploadAttempts,
			&i.SignedAt,
			&i.UploadedAt,
			&i.CreatedAt,
			&i.HashSource,
			&i.SourceS3Bucket,
			&i.SourceS3Key,
			&i.SourceContentType,
			&i.SourceSizeBytes,
			&i.SourceMetaHash,
			&i.VerificationStatus,
			&i.VerificationCheckedAt,
			&i.VerificationError,
			&i.VerificationAttempts,
			&i.VerificationNextAt,
			&i.ClientIndex,
			&i.ClientRef,
			&i.SignerIin,
			&i.SignerName,
			&i.SignerBin,
			&i.OrgName,
			&i.SignerType,
			&i.Basis,
			&i.CertSerial,
			&i.CertNotBefore,
			&i.CertNotAfter,
			&i.CaName,
			&i.OcspStatus,
			&i.TspTime,
			&i.SignFormat,
			&i.QrUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReadySessionDocuments = `-- name: ListReadySessionDocuments :many
SELECT id, session_id, document_name, source_url, target_url, target_s3_key, content_hash, cached_s3_key, signed_s3_key, cms_s3_key, status, last_error, upload_attempts, signed_at, uploaded_at, created_at, hash_source, source_s3_bucket, source_s3_key, source_content_type, source_size_bytes, source_meta_hash, verification_status, verification_checked_at, verification_error, verification_attempts, verification_next_at, client_index, client_ref, signer_iin, signer_name, signer_bin, org_name, signer_type, basis, cert_serial, cert_not_before, cert_not_after, ca_name, ocsp_status, tsp_time, sign_format, qr_url FROM signing_session_documents
WHERE session_id = $1 AND status = 'ready'
ORDER BY client_index NULLS LAST, created_at
`

func (q *Queries) ListReadySessionDocuments(ctx context.Context, sessionID uuid.UUID) ([]SigningSessionDocument, error) {
	rows, err := q.db.QueryContext(ctx, listReadySessionDocuments, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SigningSessionDocument
	for rows.Next() {
		var i SigningSessionDocument
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.DocumentName,
			&i.SourceUrl,
			&i.TargetUrl,
			&i.TargetS3Key,
			&i.ContentHash,
			&i.CachedS3Key,
			&i.SignedS3Key,
			&i.CmsS3Key,
			&i.Status,
			&i.LastError,
			&i.UploadAttempts,
			&i.SignedAt,
			&i.UploadedAt,
			&i.CreatedAt,
			&i.HashSource,
			&i.SourceS3Bucket,
			&i.SourceS3Key,
			&i.SourceContentType,
			&i.SourceSizeBytes,
			&i.SourceMetaHash,
			&i.VerificationStatus,
			&i.VerificationCheckedAt,
			&i.VerificationError,
			&i.VerificationAttempts,
			&i.VerificationNextAt,
			&i.ClientIndex,
			&i.ClientRef,
			&i.SignerIin,
			&i.SignerName,
			&i.SignerBin,
			&i.OrgName,
			&i.SignerType,
			&i.Basis,
			&i.CertSerial,
			&i.CertNotBefore,
			&i.CertNotAfter,
			&i.CaName,
			&i.OcspStatus,
			&i.TspTime,
			&i.SignFormat,
			&i.QrUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSessionDocuments = `-- name: ListSessionDocuments :many
SELECT id, session_id, document_name, source_url, target_url, target_s3_key, content_hash, cached_s3_key, signed_s3_key, cms_s3_key, status, last_error, upload_attempts, signed_at, uploaded_at, created_at, hash_source, source_s3_bucket, source_s3_key, source_content_type, source_size_bytes, source_meta_hash, verification_status, verification_checked_at, verification_error, verification_attempts, verification_next_at, client_index, client_ref, signer_iin, signer_name, signer_bin, org_name, signer_type, basis, cert_serial, cert_not_before, cert_not_after, ca_name, ocsp_status, tsp_time, sign_format, qr_url FROM signing_session_documents
WHERE session_id = $1
ORDER BY client_index NULLS LAST, created_at
`

// Порядок гарантируется: сначала по client_index (если есть), затем по
// created_at (для legacy-сессий и tie-breaker). Lovable сопоставляет
// response.documents с request.documents по индексу.
func (q *Queries) ListSessionDocuments(ctx context.Context, sessionID uuid.UUID) ([]SigningSessionDocument, error) {
	rows, err := q.db.QueryContext(ctx, listSessionDocuments, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SigningSessionDocument
	for rows.Next() {
		var i SigningSessionDocument
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.DocumentName,
			&i.SourceUrl,
			&i.TargetUrl,
			&i.TargetS3Key,
			&i.ContentHash,
			&i.CachedS3Key,
			&i.SignedS3Key,
			&i.CmsS3Key,
			&i.Status,
			&i.LastError,
			&i.UploadAttempts,
			&i.SignedAt,
			&i.UploadedAt,
			&i.CreatedAt,
			&i.HashSource,
			&i.SourceS3Bucket,
			&i.SourceS3Key,
			&i.SourceContentType,
			&i.SourceSizeBytes,
			&i.SourceMetaHash,
			&i.VerificationStatus,
			&i.VerificationCheckedAt,
			&i.VerificationError,
			&i.VerificationAttempts,
			&i.VerificationNextAt,
			&i.ClientIndex,
			&i.ClientRef,
			&i.SignerIin,
			&i.SignerName,
			&i.SignerBin,
			&i.OrgName,
			&i.SignerType,
			&i.Basis,
			&i.CertSerial,
			&i.CertNotBefore,
			&i.CertNotAfter,
			&i.CaName,
			&i.OcspStatus,
			&i.TspTime,
			&i.SignFormat,
			&i.QrUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSigningSessionDocumentsForRegistry = `-- name: ListSigningSessionDocumentsForRegistry :many
SELECT ssd.id, ssd.session_id, ssd.document_name, ssd.source_url, ssd.target_url, ssd.target_s3_key, ssd.content_hash, ssd.cached_s3_key, ssd.signed_s3_key, ssd.cms_s3_key, ssd.status, ssd.last_error, ssd.upload_attempts, ssd.signed_at, ssd.uploaded_at, ssd.created_at, ssd.hash_source, ssd.source_s3_bucket, ssd.source_s3_key, ssd.source_content_type, ssd.source_size_bytes, ssd.source_meta_hash, ssd.verification_status, ssd.verification_checked_at, ssd.verification_error, ssd.verification_attempts, ssd.verification_next_at, ssd.client_index, ssd.client_ref, ssd.signer_iin, ssd.signer_name, ssd.signer_bin, ssd.org_name, ssd.signer_type, ssd.basis, ssd.cert_serial, ssd.cert_not_before, ssd.cert_not_after, ssd.ca_name, ssd.ocsp_status, ssd.tsp_time, ssd.sign_format, ssd.qr_url, ss.tenant_id AS tenant_id, ss.application_id AS application_id,
       ss.status AS session_status, ss.expires_at AS session_expires_at
FROM signing_session_documents ssd
JOIN signing_sessions ss ON ss.id = ssd.session_id
WHERE ($1::uuid IS NULL OR ss.tenant_id = $1::uuid)
  AND ($2::text IS NULL OR ssd.status = $2::text)
ORDER BY ssd.created_at DESC
LIMIT $4 OFFSET $3
`

type ListSigningSessionDocumentsForRegistryParams struct {
	TenantID    uuid.NullUUID  `json:"tenant_id"`
	DocStatus   sql.NullString `json:"doc_status"`
	OffsetCount int32          `json:"offset_count"`
	LimitCount  int32          `json:"limit_count"`
}

type ListSigningSessionDocumentsForRegistryRow struct {
	ID                    uuid.UUID      `json:"id"`
	SessionID             uuid.UUID      `json:"session_id"`
	DocumentName          string         `json:"document_name"`
	SourceUrl             string         `json:"source_url"`
	TargetUrl             sql.NullString `json:"target_url"`
	TargetS3Key           sql.NullString `json:"target_s3_key"`
	ContentHash           sql.NullString `json:"content_hash"`
	CachedS3Key           sql.NullString `json:"cached_s3_key"`
	SignedS3Key           sql.NullString `json:"signed_s3_key"`
	CmsS3Key              sql.NullString `json:"cms_s3_key"`
	Status                string         `json:"status"`
	LastError             sql.NullString `json:"last_error"`
	UploadAttempts        int32          `json:"upload_attempts"`
	SignedAt              sql.NullTime   `json:"signed_at"`
	UploadedAt            sql.NullTime   `json:"uploaded_at"`
	CreatedAt             time.Time      `json:"created_at"`
	HashSource            string         `json:"hash_source"`
	SourceS3Bucket        sql.NullString `json:"source_s3_bucket"`
	SourceS3Key           sql.NullString `json:"source_s3_key"`
	SourceContentType     sql.NullString `json:"source_content_type"`
	SourceSizeBytes       sql.NullInt64  `json:"source_size_bytes"`
	SourceMetaHash        sql.NullString `json:"source_meta_hash"`
	VerificationStatus    sql.NullString `json:"verification_status"`
	VerificationCheckedAt sql.NullTime   `json:"verification_checked_at"`
	VerificationError     sql.NullString `json:"verification_error"`
	VerificationAttempts  int32          `json:"verification_attempts"`
	VerificationNextAt    sql.NullTime   `json:"verification_next_at"`
	ClientIndex           sql.NullInt32  `json:"client_index"`
	ClientRef             sql.NullString `json:"client_ref"`
	SignerIin             sql.NullString `json:"signer_iin"`
	SignerName            sql.NullString `json:"signer_name"`
	SignerBin             sql.NullString `json:"signer_bin"`
	OrgName               sql.NullString `json:"org_name"`
	SignerType            sql.NullString `json:"signer_type"`
	Basis                 sql.NullString `json:"basis"`
	CertSerial            sql.NullString `json:"cert_serial"`
	CertNotBefore         sql.NullTime   `json:"cert_not_before"`
	CertNotAfter          sql.NullTime   `json:"cert_not_after"`
	CaName                sql.NullString `json:"ca_name"`
	OcspStatus            sql.NullString `json:"ocsp_status"`
	TspTime               sql.NullTime   `json:"tsp_time"`
	SignFormat            sql.NullString `json:"sign_format"`
	QrUrl                 sql.NullString `json:"qr_url"`
	TenantID              uuid.UUID      `json:"tenant_id"`
	ApplicationID         sql.NullString `json:"application_id"`
	SessionStatus         string         `json:"session_status"`
	SessionExpiresAt      time.Time      `json:"session_expires_at"`
}

// Реестр подписаний (admin-only): по документам, не по сессиям — оператор
// должен видеть каждый документ отдельно. tenant_id/status — nullable
// фильтры, NULL = без фильтра.
func (q *Queries) ListSigningSessionDocumentsForRegistry(ctx context.Context, arg ListSigningSessionDocumentsForRegistryParams) ([]ListSigningSessionDocumentsForRegistryRow, error) {
	rows, err := q.db.QueryContext(ctx, listSigningSessionDocumentsForRegistry,
		arg.TenantID,
		arg.DocStatus,
		arg.OffsetCount,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSigningSessionDocumentsForRegistryRow
	for rows.Next() {
		var i ListSigningSessionDocumentsForRegistryRow
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.DocumentName,
			&i.SourceUrl,
			&i.TargetUrl,
			&i.TargetS3Key,
			&i.ContentHash,
			&i.CachedS3Key,
			&i.SignedS3Key,
			&i.CmsS3Key,
			&i.Status,
			&i.LastError,
			&i.UploadAttempts,
			&i.SignedAt,
			&i.UploadedAt,
			&i.CreatedAt,
			&i.HashSource,
			&i.SourceS3Bucket,
			&i.SourceS3Key,
			&i.SourceContentType,
			&i.SourceSizeBytes,
			&i.SourceMetaHash,
			&i.VerificationStatus,
			&i.VerificationCheckedAt,
			&i.VerificationError,
			&i.VerificationAttempts,
			&i.VerificationNextAt,
			&i.ClientIndex,
			&i.ClientRef,
			&i.SignerIin,
			&i.SignerName,
			&i.SignerBin,
			&i.OrgName,
			&i.SignerType,
			&i.Basis,
			&i.CertSerial,
			&i.CertNotBefore,
			&i.CertNotAfter,
			&i.CaName,
			&i.OcspStatus,
			&i.TspTime,
			&i.SignFormat,
			&i.QrUrl,
			&i.TenantID,
			&i.ApplicationID,
			&i.SessionStatus,
			&i.SessionExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markSessionDocumentTampered = `-- name: MarkSessionDocumentTampered :one
UPDATE signing_session_documents
SET status = 'fetch_failed',
    verification_status = 'mismatch',
    verification_error = $2,
    verification_checked_at = now()
WHERE id = $1
RETURNING id, session_id, document_name, source_url, target_url, target_s3_key, content_hash, cached_s3_key, signed_s3_key, cms_s3_key, status, last_error, upload_attempts, signed_at, uploaded_at, created_at, hash_source, source_s3_bucket, source_s3_key, source_content_type, source_size_bytes, source_meta_hash, verification_status, verification_checked_at, verification_error, verification_attempts, verification_next_at, client_index, client_ref, signer_iin, signer_name, signer_bin, org_name, signer_type, basis, cert_serial, cert_not_before, cert_not_after, ca_name, ocsp_status, tsp_time, sign_format, qr_url
`

type MarkSessionDocumentTamperedParams struct {
	ID                uuid.UUID      `json:"id"`
	VerificationError sql.NullString `json:"verification_error"`
}

// client-mode + sanity-check провалился: реально посчитанный SHA не совпал
// с клиентским hash. Документ окончательно отбракован.
func (q *Queries) MarkSessionDocumentTampered(ctx context.Context, arg MarkSessionDocumentTamperedParams) (SigningSessionDocument, error) {
	row := q.db.QueryRowContext(ctx, markSessionDocumentTampered, arg.ID, arg.VerificationError)
	var i SigningSessionDocument
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.DocumentName,
		&i.SourceUrl,
		&i.TargetUrl,
		&i.TargetS3Key,
		&i.ContentHash,
		&i.CachedS3Key,
		&i.SignedS3Key,
		&i.CmsS3Key,
		&i.Status,
		&i.LastError,
		&i.UploadAttempts,
		&i.SignedAt,
		&i.UploadedAt,
		&i.CreatedAt,
		&i.HashSource,
		&i.SourceS3Bucket,
		&i.SourceS3Key,
		&i.SourceContentType,
		&i.SourceSizeBytes,
		&i.SourceMetaHash,
		&i.VerificationStatus,
		&i.VerificationCheckedAt,
		&i.VerificationError,
		&i.VerificationAttempts,
		&i.VerificationNextAt,
		&i.ClientIndex,
		&i.ClientRef,
		&i.SignerIin,
		&i.SignerName,
		&i.SignerBin,
		&i.OrgName,
		&i.SignerType,
		&i.Basis,
		&i.CertSerial,
		&i.CertNotBefore,
		&i.CertNotAfter,
		&i.CaName,
		&i.OcspStatus,
		&i.TspTime,
		&i.SignFormat,
		&i.QrUrl,
	)
	return i, err
}

const markSessionDocumentUploaded = `-- name: MarkSessionDocumentUploaded :one
UPDATE signing_session_documents
SET status = 'uploaded', uploaded_at = now()
WHERE id = $1
RETURNING id, session_id, document_name, source_url, target_url, target_s3_key, content_hash, cached_s3_key, signed_s3_key, cms_s3_key, status, last_error, upload_attempts, signed_at, uploaded_at, created_at, hash_source, source_s3_bucket, source_s3_key, source_content_type, source_size_bytes, source_meta_hash, verification_status, verification_checked_at, verification_error, verification_attempts, verification_next_at, client_index, client_ref, signer_iin, signer_name, signer_bin, org_name, signer_type, basis, cert_serial, cert_not_before, cert_not_after, ca_name, ocsp_status, tsp_time, sign_format, qr_url
`

func (q *Queries) MarkSessionDocumentUploaded(ctx context.Context, id uuid.UUID) (SigningSessionDocument, error) {
	row := q.db.QueryRowContext(ctx, markSessionDocumentUploaded, id)
	var i SigningSessionDocument
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.DocumentName,
		&i.SourceUrl,
		&i.TargetUrl,
		&i.TargetS3Key,
		&i.ContentHash,
		&i.CachedS3Key,
		&i.SignedS3Key,
		&i.CmsS3Key,
		&i.Status,
		&i.LastError,
		&i.UploadAttempts,
		&i.SignedAt,
		&i.UploadedAt,
		&i.CreatedAt,
		&i.HashSource,
		&i.SourceS3Bucket,
		&i.SourceS3Key,
		&i.SourceContentType,
		&i.SourceSizeBytes,
		&i.SourceMetaHash,
		&i.VerificationStatus,
		&i.VerificationCheckedAt,
		&i.VerificationError,
		&i.VerificationAttempts,
		&i.VerificationNextAt,
		&i.ClientIndex,
		&i.ClientRef,
		&i.SignerIin,
		&i.SignerName,
		&i.SignerBin,
		&i.OrgName,
		&i.SignerType,
		&i.Basis,
		&i.CertSerial,
		&i.CertNotBefore,
		&i.CertNotAfter,
		&i.CaName,
		&i.OcspStatus,
		&i.TspTime,
		&i.SignFormat,
		&i.QrUrl,
	)
	return i, err
}

const markSessionDocumentVerificationPending = `-- name: MarkSessionDocumentVerificationPending :exec
UPDATE signing_session_documents
SET verification_status = 'pending',
    verification_next_at = $2
WHERE id = $1
`

type MarkSessionDocumentVerificationPendingParams struct {
	ID                 uuid.UUID    `json:"id"`
	VerificationNextAt sql.NullTime `json:"verification_next_at"`
}

// Вызывается из /sign/complete после успешной sync-сверки messageDigest.
// Первая проверка асинхронным воркером откладывается на InitialDelay секунд.
func (q *Queries) MarkSessionDocumentVerificationPending(ctx context.Context, arg MarkSessionDocumentVerificationPendingParams) error {
	_, err := q.db.ExecContext(ctx, markSessionDocumentVerificationPending, arg.ID, arg.VerificationNextAt)
	return err
}

const recalcSessionVerification = `-- name: RecalcSessionVerification :exec
UPDATE signing_sessions s
SET verification_status = (
    SELECT CASE
        WHEN bool_or(ssd.verification_status = 'mismatch')       THEN 'mismatch'
        WHEN bool_or(ssd.verification_status = 'unavailable')    THEN 'unavailable'
        WHEN bool_or(ssd.verification_status IN ('pending','retrying')) THEN 'pending'
        WHEN bool_and(ssd.verification_status = 'verified')      THEN 'verified'
        ELSE NULL
    END
    FROM signing_session_documents ssd
    WHERE ssd.session_id = s.id
)
WHERE s.id = $1
`

// Worst-of агрегат: любой не-'verified' документ перетягивает статус сессии.
// Приоритет: mismatch > unavailable > pending > verified. Сессии без verification-
// атрибутов у документов не трогаем.
func (q *Queries) RecalcSessionVerification(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, recalcSessionVerification, id)
	return err
}

const resetSessionDocumentForRetry = `-- name: ResetSessionDocumentForRetry :one
UPDATE signing_session_documents
SET status = 'signed', upload_attempts = 0, last_error = NULL, target_url = $2
WHERE id = $1
RETURNING id, session_id, document_name, source_url, target_url, target_s3_key, content_hash, cached_s3_key, signed_s3_key, cms_s3_key, status, last_error, upload_attempts, signed_at, uploaded_at, created_at, hash_source, source_s3_bucket, source_s3_key, source_content_type, source_size_bytes, source_meta_hash, verification_status, verification_checked_at, verification_error, verification_attempts, verification_next_at, client_index, client_ref, signer_iin, signer_name, signer_bin, org_name, signer_type, basis, cert_serial, cert_not_before, cert_not_after, ca_name, ocsp_status, tsp_time, sign_format, qr_url
`

type ResetSessionDocumentForRetryParams struct {
	ID        uuid.UUID      `json:"id"`
	TargetUrl sql.NullString `json:"target_url"`
}

func (q *Queries) ResetSessionDocumentForRetry(ctx context.Context, arg ResetSessionDocumentForRetryParams) (SigningSessionDocument, error) {
	row := q.db.QueryRowContext(ctx, resetSessionDocumentForRetry, arg.ID, arg.TargetUrl)
	var i SigningSessionDocument
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.DocumentName,
		&i.SourceUrl,
		&i.TargetUrl,
		&i.TargetS3Key,
		&i.ContentHash,
		&i.CachedS3Key,
		&i.SignedS3Key,
		&i.CmsS3Key,
		&i.Status,
		&i.LastError,
		&i.UploadAttempts,
		&i.SignedAt,
		&i.UploadedAt,
		&i.CreatedAt,
		&i.HashSource,
		&i.SourceS3Bucket,
		&i.SourceS3Key,
		&i.SourceContentType,
		&i.SourceSizeBytes,
		&i.SourceMetaHash,
		&i.VerificationStatus,
		&i.VerificationCheckedAt,
		&i.VerificationError,
		&i.VerificationAttempts,
		&i.VerificationNextAt,
		&i.ClientIndex,
		&i.ClientRef,
		&i.SignerIin,
		&i.SignerName,
		&i.SignerBin,
		&i.OrgName,
		&i.SignerType,
		&i.Basis,
		&i.CertSerial,
		&i.CertNotBefore,
		&i.CertNotAfter,
		&i.CaName,
		&i.OcspStatus,
		&i.TspTime,
		&i.SignFormat,
		&i.QrUrl,
	)
	return i, err
}

const updateDocumentVerification = `-- name: UpdateDocumentVerification :exec
UPDATE signing_session_documents
SET verification_status = $2,
    verification_checked_at = now(),
    verification_attempts = verification_attempts + 1,
    verification_error = $3,
    verification_next_at = $4,
    source_meta_hash = COALESCE($5, source_meta_hash)
WHERE id = $1
`

type UpdateDocumentVerificationParams struct {
	ID                 uuid.UUID      `json:"id"`
	VerificationStatus sql.NullString `json:"verification_status"`
	VerificationError  sql.NullString `json:"verification_error"`
	VerificationNextAt sql.NullTime   `json:"verification_next_at"`
	SourceMetaHash     sql.NullString `json:"source_meta_hash"`
}

// Финальная или промежуточная запись результата проверки. attempts инкрементируется
// атомарно. error/source_meta_hash могут быть NULL.
func (q *Queries) UpdateDocumentVerification(ctx context.Context, arg UpdateDocumentVerificationParams) error {
	_, err := q.db.ExecContext(ctx, updateDocumentVerification,
		arg.ID,
		arg.VerificationStatus,
		arg.VerificationError,
		arg.VerificationNextAt,
		arg.SourceMetaHash,
	)
	return err
}

const updateSessionDocumentAfterFetch = `-- name: UpdateSessionDocumentAfterFetch :one
UPDATE signing_session_documents
SET content_hash = $2, cached_s3_key = $3, status = 'ready'
WHERE id = $1
RETURNING id, session_id, document_name, source_url, target_url, target_s3_key, content_hash, cached_s3_key, signed_s3_key, cms_s3_key, status, last_error, upload_attempts, signed_at, uploaded_at, created_at, hash_source, source_s3_bucket, source_s3_key, source_content_type, source_size_bytes, source_meta_hash, verification_status, verification_checked_at, verification_error, verification_attempts, verification_next_at, client_index, client_ref, signer_iin, signer_name, signer_bin, org_name, signer_type, basis, cert_serial, cert_not_before, cert_not_after, ca_name, ocsp_status, tsp_time, sign_format, qr_url
`

type UpdateSessionDocumentAfterFetchParams struct {
	ID          uuid.UUID      `json:"id"`
	ContentHash sql.NullString `json:"content_hash"`
	CachedS3Key sql.NullString `json:"cached_s3_key"`
}

// legacy: пишет content_hash из посчитанного фетчером значения.
func (q *Queries) UpdateSessionDocumentAfterFetch(ctx context.Context, arg UpdateSessionDocumentAfterFetchParams) (SigningSessionDocument, error) {
	row := q.db.QueryRowContext(ctx, updateSessionDocumentAfterFetch, arg.ID, arg.ContentHash, arg.CachedS3Key)
	var i SigningSessionDocument
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.DocumentName,
		&i.SourceUrl,
		&i.TargetUrl,
		&i.TargetS3Key,
		&i.ContentHash,
		&i.CachedS3Key,
		&i.SignedS3Key,
		&i.CmsS3Key,
		&i.Status,
		&i.LastError,
		&i.UploadAttempts,
		&i.SignedAt,
		&i.UploadedAt,
		&i.CreatedAt,
		&i.HashSource,
		&i.SourceS3Bucket,
		&i.SourceS3Key,
		&i.SourceContentType,
		&i.SourceSizeBytes,
		&i.SourceMetaHash,
		&i.VerificationStatus,
		&i.VerificationCheckedAt,
		&i.VerificationError,
		&i.VerificationAttempts,
		&i.VerificationNextAt,
		&i.ClientIndex,
		&i.ClientRef,
		&i.SignerIin,
		&i.SignerName,
		&i.SignerBin,
		&i.OrgName,
		&i.SignerType,
		&i.Basis,
		&i.CertSerial,
		&i.CertNotBefore,
		&i.CertNotAfter,
		&i.CaName,
		&i.OcspStatus,
		&i.TspTime,
		&i.SignFormat,
		&i.QrUrl,
	)
	return i, err
}

const updateSessionDocumentAfterFetchKeepHash = `-- name: UpdateSessionDocumentAfterFetchKeepHash :one
UPDATE signing_session_documents
SET cached_s3_key = $2, status = 'ready'
WHERE id = $1
RETURNING id, session_id, document_name, source_url, target_url, target_s3_key, content_hash, cached_s3_key, signed_s3_key, cms_s3_key, status, last_error, upload_attempts, signed_at, uploaded_at, created_at, hash_source, source_s3_bucket, source_s3_key, source_content_type, source_size_bytes, source_meta_hash, verification_status, verification_checked_at, verification_error, verification_attempts, verification_next_at, client_index, client_ref, signer_iin, signer_name, signer_bin, org_name, signer_type, basis, cert_serial, cert_not_before, cert_not_after, ca_name, ocsp_status, tsp_time, sign_format, qr_url
`

type UpdateSessionDocumentAfterFetchKeepHashParams struct {
	ID          uuid.UUID      `json:"id"`
	CachedS3Key sql.NullString `json:"cached_s3_key"`
}

// client-mode: hash уже записан, фетчер только кэширует PDF.
func (q *Queries) UpdateSessionDocumentAfterFetchKeepHash(ctx context.Context, arg UpdateSessionDocumentAfterFetchKeepHashParams) (SigningSessionDocument, error) {
	row := q.db.QueryRowContext(ctx, updateSessionDocumentAfterFetchKeepHash, arg.ID, arg.CachedS3Key)
	var i SigningSessionDocument
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.DocumentName,
		&i.SourceUrl,
		&i.TargetUrl,
		&i.TargetS3Key,
		&i.ContentHash,
		&i.CachedS3Key,
		&i.SignedS3Key,
		&i.CmsS3Key,
		&i.Status,
		&i.LastError,
		&i.UploadAttempts,
		&i.SignedAt,
		&i.UploadedAt,
		&i.CreatedAt,
		&i.HashSource,
		&i.SourceS3Bucket,
		&i.SourceS3Key,
		&i.SourceContentType,
		&i.SourceSizeBytes,
		&i.SourceMetaHash,
		&i.VerificationStatus,
		&i.VerificationCheckedAt,
		&i.VerificationError,
		&i.VerificationAttempts,
		&i.VerificationNextAt,
		&i.ClientIndex,
		&i.ClientRef,
		&i.SignerIin,
		&i.SignerName,
		&i.SignerBin,
		&i.OrgName,
		&i.SignerType,
		&i.Basis,
		&i.CertSerial,
		&i.CertNotBefore,
		&i.CertNotAfter,
		&i.CaName,
		&i.OcspStatus,
		&i.TspTime,
		&i.SignFormat,
		&i.QrUrl,
	)
	return i, err
}

const updateSessionDocumentAfterSign = `-- name: UpdateSessionDocumentAfterSign :one
UPDATE signing_session_documents
SET cms_s3_key = $2, signed_s3_key = $3, status = 'signed', signed_at = now()
WHERE id = $1
RETURNING id, session_id, document_name, source_url, target_url, target_s3_key, content_hash, cached_s3_key, signed_s3_key, cms_s3_key, status, last_error, upload_attempts, signed_at, uploaded_at, created_at, hash_source, source_s3_bucket, source_s3_key, source_content_type, source_size_bytes, source_meta_hash, verification_status, verification_checked_at, verification_error, verification_attempts, verification_next_at, client_index, client_ref, signer_iin, signer_name, signer_bin, org_name, signer_type, basis, cert_serial, cert_not_before, cert_not_after, ca_name, ocsp_status, tsp_time, sign_format, qr_url
`

type UpdateSessionDocumentAfterSignParams struct {
	ID          uuid.UUID      `json:"id"`
	CmsS3Key    sql.NullString `json:"cms_s3_key"`
	SignedS3Key sql.NullString `json:"signed_s3_key"`
}

func (q *Queries) UpdateSessionDocumentAfterSign(ctx context.Context, arg UpdateSessionDocumentAfterSignParams) (SigningSessionDocument, error) {
	row := q.db.QueryRowContext(ctx, updateSessionDocumentAfterSign, arg.ID, arg.CmsS3Key, arg.SignedS3Key)
	var i SigningSessionDocument
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.DocumentName,
		&i.SourceUrl,
		&i.TargetUrl,
		&i.TargetS3Key,
		&i.ContentHash,
		&i.CachedS3Key,
		&i.SignedS3Key,
		&i.CmsS3Key,
		&i.Status,
		&i.LastError,
		&i.UploadAttempts,
		&i.SignedAt,
		&i.UploadedAt,
		&i.CreatedAt,
		&i.HashSource,
		&i.SourceS3Bucket,
		&i.SourceS3Key,
		&i.SourceContentType,
		&i.SourceSizeBytes,
		&i.SourceMetaHash,
		&i.VerificationStatus,
		&i.VerificationCheckedAt,
		&i.VerificationError,
		&i.VerificationAttempts,
		&i.VerificationNextAt,
		&i.ClientIndex,
		&i.ClientRef,
		&i.SignerIin,
		&i.SignerName,
		&i.SignerBin,
		&i.OrgName,
		&i.SignerType,
		&i.Basis,
		&i.CertSerial,
		&i.CertNotBefore,
		&i.CertNotAfter,
		&i.CaName,
		&i.OcspStatus,
		&i.TspTime,
		&i.SignFormat,
		&i.QrUrl,
	)
	return i, err
}

const updateSessionDocumentSignerInfo = `-- name: UpdateSessionDocumentSignerInfo :one
UPDATE signing_session_documents
SET signer_iin = $2, signer_name = $3, signer_bin = $4, org_name = $5,
    signer_type = $6, basis = $7, cert_serial = $8, cert_not_before = $9,
    cert_not_after = $10, ca_name = $11, ocsp_status = $12, tsp_time = $13,
    sign_format = $14, qr_url = $15
WHERE id = $1
RETURNING id, session_id, document_name, source_url, target_url, target_s3_key, content_hash, cached_s3_key, signed_s3_key, cms_s3_key, status, last_error, upload_attempts, signed_at, uploaded_at, created_at, hash_source, source_s3_bucket, source_s3_key, source_content_type, source_size_bytes, source_meta_hash, verification_status, verification_checked_at, verification_error, verification_attempts, verification_next_at, client_index, client_ref, signer_iin, signer_name, signer_bin, org_name, signer_type, basis, cert_serial, cert_not_before, cert_not_after, ca_name, ocsp_status, tsp_time, sign_format, qr_url
`

type UpdateSessionDocumentSignerInfoParams struct {
	ID            uuid.UUID      `json:"id"`
	SignerIin     sql.NullString `json:"signer_iin"`
	SignerName    sql.NullString `json:"signer_name"`
	SignerBin     sql.NullString `json:"signer_bin"`
	OrgName       sql.NullString `json:"org_name"`
	SignerType    sql.NullString `json:"signer_type"`
	Basis         sql.NullString `json:"basis"`
	CertSerial    sql.NullString `json:"cert_serial"`
	CertNotBefore sql.NullTime   `json:"cert_not_before"`
	CertNotAfter  sql.NullTime   `json:"cert_not_after"`
	CaName        sql.NullString `json:"ca_name"`
	OcspStatus    sql.NullString `json:"ocsp_status"`
	TspTime       sql.NullTime   `json:"tsp_time"`
	SignFormat    sql.NullString `json:"sign_format"`
	QrUrl         sql.NullString `json:"qr_url"`
}

// Персистит ncanode.VerifyResult + реальный verify QR-URL. Non-fatal при
// ошибке (вызывающий код логирует и продолжает — PDF уже собран корректно).
func (q *Queries) UpdateSessionDocumentSignerInfo(ctx context.Context, arg UpdateSessionDocumentSignerInfoParams) (SigningSessionDocument, error) {
	row := q.db.QueryRowContext(ctx, updateSessionDocumentSignerInfo,
		arg.ID,
		arg.SignerIin,
		arg.SignerName,
		arg.SignerBin,
		arg.OrgName,
		arg.SignerType,
		arg.Basis,
		arg.CertSerial,
		arg.CertNotBefore,
		arg.CertNotAfter,
		arg.CaName,
		arg.OcspStatus,
		arg.TspTime,
		arg.SignFormat,
		arg.QrUrl,
	)
	var i SigningSessionDocument
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.DocumentName,
		&i.SourceUrl,
		&i.TargetUrl,
		&i.TargetS3Key,
		&i.ContentHash,
		&i.CachedS3Key,
		&i.SignedS3Key,
		&i.CmsS3Key,
		&i.Status,
		&i.LastError,
		&i.UploadAttempts,
		&i.SignedAt,
		&i.UploadedAt,
		&i.CreatedAt,
		&i.HashSource,
		&i.SourceS3Bucket,
		&i.SourceS3Key,
		&i.SourceContentType,
		&i.SourceSizeBytes,
		&i.SourceMetaHash,
		&i.VerificationStatus,
		&i.VerificationCheckedAt,
		&i.VerificationError,
		&i.VerificationAttempts,
		&i.VerificationNextAt,
		&i.ClientIndex,
		&i.ClientRef,
		&i.SignerIin,
		&i.SignerName,
		&i.SignerBin,
		&i.OrgName,
		&i.SignerType,
		&i.Basis,
		&i.CertSerial,
		&i.CertNotBefore,
		&i.CertNotAfter,
		&i.CaName,
		&i.OcspStatus,
		&i.TspTime,
		&i.SignFormat,
		&i.QrUrl,
	)
	return i, err
}

const updateSessionDocumentStatus = `-- name: UpdateSessionDocumentStatus :one
UPDATE signing_session_documents
SET status = $2, last_error = $3
WHERE id = $1
RETURNING id, session_id, document_name, source_url, target_url, target_s3_key, content_hash, cached_s3_key, signed_s3_key, cms_s3_key, status, last_error, upload_attempts, signed_at, uploaded_at, created_at, hash_source, source_s3_bucket, source_s3_key, source_content_type, source_size_bytes, source_meta_hash, verification_status, verification_checked_at, verification_error, verification_attempts, verification_next_at, client_index, client_ref, signer_iin, signer_name, signer_bin, org_name, signer_type, basis, cert_serial, cert_not_before, cert_not_after, ca_name, ocsp_status, tsp_time, sign_format, qr_url
`

type UpdateSessionDocumentStatusParams struct {
	ID        uuid.UUID      `json:"id"`
	Status    string         `json:"status"`
	LastError sql.NullString `json:"last_error"`
}

func (q *Queries) UpdateSessionDocumentStatus(ctx context.Context, arg UpdateSessionDocumentStatusParams) (SigningSessionDocument, error) {
	row := q.db.QueryRowContext(ctx, updateSessionDocumentStatus, arg.ID, arg.Status, arg.LastError)
	var i SigningSessionDocument
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.DocumentName,
		&i.SourceUrl,
		&i.TargetUrl,
		&i.TargetS3Key,
		&i.ContentHash,
		&i.CachedS3Key,
		&i.SignedS3Key,
		&i.CmsS3Key,
		&i.Status,
		&i.LastError,
		&i.UploadAttempts,
		&i.SignedAt,
		&i.UploadedAt,
		&i.CreatedAt,
		&i.HashSource,
		&i.SourceS3Bucket,
		&i.SourceS3Key,
		&i.SourceContentType,
		&i.SourceSizeBytes,
		&i.SourceMetaHash,
		&i.VerificationStatus,
		&i.VerificationCheckedAt,
		&i.VerificationError,
		&i.VerificationAttempts,
		&i.VerificationNextAt,
		&i.ClientIndex,
		&i.ClientRef,
		&i.SignerIin,
		&i.SignerName,
		&i.SignerBin,
		&i.OrgName,
		&i.SignerType,
		&i.Basis,
		&i.CertSerial,
		&i.CertNotBefore,
		&i.CertNotAfter,
		&i.CaName,
		&i.OcspStatus,
		&i.TspTime,
		&i.SignFormat,
		&i.QrUrl,
	)
	return i, err
}

const updateSessionDocumentTargetURL = `-- name: UpdateSessionDocumentTargetURL :one
UPDATE signing_session_documents
SET target_url = $2
WHERE id = $1
RETURNING id, session_id, document_name, source_url, target_url, target_s3_key, content_hash, cached_s3_key, signed_s3_key, cms_s3_key, status, last_error, upload_attempts, signed_at, uploaded_at, created_at, hash_source, source_s3_bucket, source_s3_key, source_content_type, source_size_bytes, source_meta_hash, verification_status, verification_checked_at, verification_error, verification_attempts, verification_next_at, client_index, client_ref, signer_iin, signer_name, signer_bin, org_name, signer_type, basis, cert_serial, cert_not_before, cert_not_after, ca_name, ocsp_status, tsp_time, sign_format, qr_url
`

type UpdateSessionDocumentTargetURLParams struct {
	ID        uuid.UUID      `json:"id"`
	TargetUrl sql.NullString `json:"target_url"`
}

func (q *Queries) UpdateSessionDocumentTargetURL(ctx context.Context, arg UpdateSessionDocumentTargetURLParams) (SigningSessionDocument, error) {
	row := q.db.QueryRowContext(ctx, updateSessionDocumentTargetURL, arg.ID, arg.TargetUrl)
	var i SigningSessionDocument
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.DocumentName,
		&i.SourceUrl,
		&i.TargetUrl,
		&i.TargetS3Key,
		&i.ContentHash,
		&i.CachedS3Key,
		&i.SignedS3Key,
		&i.CmsS3Key,
		&i.Status,
		&i.LastError,
		&i.UploadAttempts,
		&i.SignedAt,
		&i.UploadedAt,
		&i.CreatedAt,
		&i.HashSource,
		&i.SourceS3Bucket,
		&i.SourceS3Key,
		&i.SourceContentType,
		&i.SourceSizeBytes,
		&i.SourceMetaHash,
		&i.VerificationStatus,
		&i.VerificationCheckedAt,
		&i.VerificationError,
		&i.VerificationAttempts,
		&i.VerificationNextAt,
		&i.ClientIndex,
		&i.ClientRef,
		&i.SignerIin,
		&i.SignerName,
		&i.SignerBin,
		&i.OrgName,
		&i.SignerType,
		&i.Basis,
		&i.CertSerial,
		&i.CertNotBefore,
		&i.CertNotAfter,
		&i.CaName,
		&i.OcspStatus,
		&i.TspTime,
		&i.SignFormat,
		&i.QrUrl,
	)
	return i, err
}

const updateSigningSessionStatus = `-- name: UpdateSigningSessionStatus :one
UPDATE signing_sessions
SET status = $2, updated_at = now()
WHERE id = $1
RETURNING id, tenant_id, application_id, signer_role, callback_url, callback_secret, status, expires_at, created_at, updated_at, verification_status
`

type UpdateSigningSessionStatusParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

func (q *Queries) UpdateSigningSessionStatus(ctx context.Context, arg UpdateSigningSessionStatusParams) (SigningSession, error) {
	row := q.db.QueryRowContext(ctx, updateSigningSessionStatus, arg.ID, arg.Status)
	var i SigningSession
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ApplicationID,
		&i.SignerRole,
		&i.CallbackUrl,
		&i.CallbackSecret,
		&i.Status,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.VerificationStatus,
	)
	return i, err
}
