// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: signing_sessions.sql

package repository

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createSigningSession = `-- name: CreateSigningSession :one
INSERT INTO signing_sessions (
    tenant_id, application_id, signer_role, callback_url, callback_secret, status, expires_at
) VALUES (
    $1, $2, $3, $4, $5, 'pending', COALESCE($6, now() + INTERVAL '2 hours')
)
RETURNING id, tenant_id, application_id, signer_role, callback_url, callback_secret, status, expires_at, created_at, updated_at
`

type CreateSigningSessionParams struct {
	TenantID       uuid.UUID      `json:"tenant_id"`
	ApplicationID  sql.NullString `json:"application_id"`
	SignerRole     string         `json:"signer_role"`
	CallbackUrl    sql.NullString `json:"callback_url"`
	CallbackSecret sql.NullString `json:"callback_secret"`
	Column6        interface{}    `json:"column_6"`
}

func (q *Queries) CreateSigningSession(ctx context.Context, arg CreateSigningSessionParams) (SigningSession, error) {
	row := q.db.QueryRowContext(ctx, createSigningSession,
		arg.TenantID,
		arg.ApplicationID,
		arg.SignerRole,
		arg.CallbackUrl,
		arg.CallbackSecret,
		arg.Column6,
	)
	var i SigningSession
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ApplicationID,
		&i.SignerRole,
		&i.CallbackUrl,
		&i.CallbackSecret,
		&i.Status,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createSigningSessionDocument = `-- name: CreateSigningSessionDocument :one
INSERT INTO signing_session_documents (
    session_id, document_name, source_url, target_url, target_s3_key, content_hash, status
) VALUES (
    $1, $2, $3, $4, $5, '', 'pending'
)
RETURNING id, session_id, document_name, source_url, target_url, target_s3_key, content_hash, cached_s3_key, signed_s3_key, cms_s3_key, status, last_error, upload_attempts, signed_at, uploaded_at, created_at
`

type CreateSigningSessionDocumentParams struct {
	SessionID    uuid.UUID      `json:"session_id"`
	DocumentName string         `json:"document_name"`
	SourceUrl    string         `json:"source_url"`
	TargetUrl    sql.NullString `json:"target_url"`
	TargetS3Key  sql.NullString `json:"target_s3_key"`
}

func (q *Queries) CreateSigningSessionDocument(ctx context.Context, arg CreateSigningSessionDocumentParams) (SigningSessionDocument, error) {
	row := q.db.QueryRowContext(ctx, createSigningSessionDocument,
		arg.SessionID,
		arg.DocumentName,
		arg.SourceUrl,
		arg.TargetUrl,
		arg.TargetS3Key,
	)
	var i SigningSessionDocument
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.DocumentName,
		&i.SourceUrl,
		&i.TargetUrl,
		&i.TargetS3Key,
		&i.ContentHash,
		&i.CachedS3Key,
		&i.SignedS3Key,
		&i.CmsS3Key,
		&i.Status,
		&i.LastError,
		&i.UploadAttempts,
		&i.SignedAt,
		&i.UploadedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getExpiredSessions = `-- name: GetExpiredSessions :many
SELECT id, tenant_id, application_id, signer_role, callback_url, callback_secret, status, expires_at, created_at, updated_at FROM signing_sessions
WHERE expires_at < now()
  AND status NOT IN ('completed', 'failed', 'expired')
ORDER BY expires_at
LIMIT 100
`

func (q *Queries) GetExpiredSessions(ctx context.Context) ([]SigningSession, error) {
	rows, err := q.db.QueryContext(ctx, getExpiredSessions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SigningSession
	for rows.Next() {
		var i SigningSession
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ApplicationID,
			&i.SignerRole,
			&i.CallbackUrl,
			&i.CallbackSecret,
			&i.Status,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPendingFetchSessionDocuments = `-- name: GetPendingFetchSessionDocuments :many
SELECT ssd.id, ssd.session_id, ssd.document_name, ssd.source_url, ssd.target_url, ssd.target_s3_key, ssd.content_hash, ssd.cached_s3_key, ssd.signed_s3_key, ssd.cms_s3_key, ssd.status, ssd.last_error, ssd.upload_attempts, ssd.signed_at, ssd.uploaded_at, ssd.created_at FROM signing_session_documents ssd
JOIN signing_sessions ss ON ss.id = ssd.session_id
WHERE ssd.status = 'pending'
  AND ss.status NOT IN ('expired', 'failed', 'completed')
  AND ss.expires_at > now()
ORDER BY ssd.created_at
LIMIT 20
`

func (q *Queries) GetPendingFetchSessionDocuments(ctx context.Context) ([]SigningSessionDocument, error) {
	rows, err := q.db.QueryContext(ctx, getPendingFetchSessionDocuments)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SigningSessionDocument
	for rows.Next() {
		var i SigningSessionDocument
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.DocumentName,
			&i.SourceUrl,
			&i.TargetUrl,
			&i.TargetS3Key,
			&i.ContentHash,
			&i.CachedS3Key,
			&i.SignedS3Key,
			&i.CmsS3Key,
			&i.Status,
			&i.LastError,
			&i.UploadAttempts,
			&i.SignedAt,
			&i.UploadedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSigningSession = `-- name: GetSigningSession :one
SELECT id, tenant_id, application_id, signer_role, callback_url, callback_secret, status, expires_at, created_at, updated_at FROM signing_sessions
WHERE id = $1 AND tenant_id = $2
`

type GetSigningSessionParams struct {
	ID       uuid.UUID `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

func (q *Queries) GetSigningSession(ctx context.Context, arg GetSigningSessionParams) (SigningSession, error) {
	row := q.db.QueryRowContext(ctx, getSigningSession, arg.ID, arg.TenantID)
	var i SigningSession
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ApplicationID,
		&i.SignerRole,
		&i.CallbackUrl,
		&i.CallbackSecret,
		&i.Status,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSigningSessionByID = `-- name: GetSigningSessionByID :one
SELECT id, tenant_id, application_id, signer_role, callback_url, callback_secret, status, expires_at, created_at, updated_at FROM signing_sessions
WHERE id = $1
`

func (q *Queries) GetSigningSessionByID(ctx context.Context, id uuid.UUID) (SigningSession, error) {
	row := q.db.QueryRowContext(ctx, getSigningSessionByID, id)
	var i SigningSession
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ApplicationID,
		&i.SignerRole,
		&i.CallbackUrl,
		&i.CallbackSecret,
		&i.Status,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSigningSessionDocument = `-- name: GetSigningSessionDocument :one
SELECT id, session_id, document_name, source_url, target_url, target_s3_key, content_hash, cached_s3_key, signed_s3_key, cms_s3_key, status, last_error, upload_attempts, signed_at, uploaded_at, created_at FROM signing_session_documents
WHERE id = $1
`

func (q *Queries) GetSigningSessionDocument(ctx context.Context, id uuid.UUID) (SigningSessionDocument, error) {
	row := q.db.QueryRowContext(ctx, getSigningSessionDocument, id)
	var i SigningSessionDocument
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.DocumentName,
		&i.SourceUrl,
		&i.TargetUrl,
		&i.TargetS3Key,
		&i.ContentHash,
		&i.CachedS3Key,
		&i.SignedS3Key,
		&i.CmsS3Key,
		&i.Status,
		&i.LastError,
		&i.UploadAttempts,
		&i.SignedAt,
		&i.UploadedAt,
		&i.CreatedAt,
	)
	return i, err
}

const incrementSessionDocumentUploadAttempts = `-- name: IncrementSessionDocumentUploadAttempts :one
UPDATE signing_session_documents
SET upload_attempts = upload_attempts + 1, last_error = $2
WHERE id = $1
RETURNING id, session_id, document_name, source_url, target_url, target_s3_key, content_hash, cached_s3_key, signed_s3_key, cms_s3_key, status, last_error, upload_attempts, signed_at, uploaded_at, created_at
`

type IncrementSessionDocumentUploadAttemptsParams struct {
	ID        uuid.UUID      `json:"id"`
	LastError sql.NullString `json:"last_error"`
}

func (q *Queries) IncrementSessionDocumentUploadAttempts(ctx context.Context, arg IncrementSessionDocumentUploadAttemptsParams) (SigningSessionDocument, error) {
	row := q.db.QueryRowContext(ctx, incrementSessionDocumentUploadAttempts, arg.ID, arg.LastError)
	var i SigningSessionDocument
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.DocumentName,
		&i.SourceUrl,
		&i.TargetUrl,
		&i.TargetS3Key,
		&i.ContentHash,
		&i.CachedS3Key,
		&i.SignedS3Key,
		&i.CmsS3Key,
		&i.Status,
		&i.LastError,
		&i.UploadAttempts,
		&i.SignedAt,
		&i.UploadedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listReadySessionDocuments = `-- name: ListReadySessionDocuments :many
SELECT id, session_id, document_name, source_url, target_url, target_s3_key, content_hash, cached_s3_key, signed_s3_key, cms_s3_key, status, last_error, upload_attempts, signed_at, uploaded_at, created_at FROM signing_session_documents
WHERE session_id = $1 AND status = 'ready'
ORDER BY created_at
`

func (q *Queries) ListReadySessionDocuments(ctx context.Context, sessionID uuid.UUID) ([]SigningSessionDocument, error) {
	rows, err := q.db.QueryContext(ctx, listReadySessionDocuments, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SigningSessionDocument
	for rows.Next() {
		var i SigningSessionDocument
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.DocumentName,
			&i.SourceUrl,
			&i.TargetUrl,
			&i.TargetS3Key,
			&i.ContentHash,
			&i.CachedS3Key,
			&i.SignedS3Key,
			&i.CmsS3Key,
			&i.Status,
			&i.LastError,
			&i.UploadAttempts,
			&i.SignedAt,
			&i.UploadedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSessionDocuments = `-- name: ListSessionDocuments :many
SELECT id, session_id, document_name, source_url, target_url, target_s3_key, content_hash, cached_s3_key, signed_s3_key, cms_s3_key, status, last_error, upload_attempts, signed_at, uploaded_at, created_at FROM signing_session_documents
WHERE session_id = $1
ORDER BY created_at
`

func (q *Queries) ListSessionDocuments(ctx context.Context, sessionID uuid.UUID) ([]SigningSessionDocument, error) {
	rows, err := q.db.QueryContext(ctx, listSessionDocuments, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SigningSessionDocument
	for rows.Next() {
		var i SigningSessionDocument
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.DocumentName,
			&i.SourceUrl,
			&i.TargetUrl,
			&i.TargetS3Key,
			&i.ContentHash,
			&i.CachedS3Key,
			&i.SignedS3Key,
			&i.CmsS3Key,
			&i.Status,
			&i.LastError,
			&i.UploadAttempts,
			&i.SignedAt,
			&i.UploadedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markSessionDocumentUploaded = `-- name: MarkSessionDocumentUploaded :one
UPDATE signing_session_documents
SET status = 'uploaded', uploaded_at = now()
WHERE id = $1
RETURNING id, session_id, document_name, source_url, target_url, target_s3_key, content_hash, cached_s3_key, signed_s3_key, cms_s3_key, status, last_error, upload_attempts, signed_at, uploaded_at, created_at
`

func (q *Queries) MarkSessionDocumentUploaded(ctx context.Context, id uuid.UUID) (SigningSessionDocument, error) {
	row := q.db.QueryRowContext(ctx, markSessionDocumentUploaded, id)
	var i SigningSessionDocument
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.DocumentName,
		&i.SourceUrl,
		&i.TargetUrl,
		&i.TargetS3Key,
		&i.ContentHash,
		&i.CachedS3Key,
		&i.SignedS3Key,
		&i.CmsS3Key,
		&i.Status,
		&i.LastError,
		&i.UploadAttempts,
		&i.SignedAt,
		&i.UploadedAt,
		&i.CreatedAt,
	)
	return i, err
}

const resetSessionDocumentForRetry = `-- name: ResetSessionDocumentForRetry :one
UPDATE signing_session_documents
SET status = 'signed', upload_attempts = 0, last_error = NULL, target_url = $2
WHERE id = $1
RETURNING id, session_id, document_name, source_url, target_url, target_s3_key, content_hash, cached_s3_key, signed_s3_key, cms_s3_key, status, last_error, upload_attempts, signed_at, uploaded_at, created_at
`

type ResetSessionDocumentForRetryParams struct {
	ID        uuid.UUID      `json:"id"`
	TargetUrl sql.NullString `json:"target_url"`
}

func (q *Queries) ResetSessionDocumentForRetry(ctx context.Context, arg ResetSessionDocumentForRetryParams) (SigningSessionDocument, error) {
	row := q.db.QueryRowContext(ctx, resetSessionDocumentForRetry, arg.ID, arg.TargetUrl)
	var i SigningSessionDocument
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.DocumentName,
		&i.SourceUrl,
		&i.TargetUrl,
		&i.TargetS3Key,
		&i.ContentHash,
		&i.CachedS3Key,
		&i.SignedS3Key,
		&i.CmsS3Key,
		&i.Status,
		&i.LastError,
		&i.UploadAttempts,
		&i.SignedAt,
		&i.UploadedAt,
		&i.CreatedAt,
	)
	return i, err
}

const updateSessionDocumentAfterFetch = `-- name: UpdateSessionDocumentAfterFetch :one
UPDATE signing_session_documents
SET content_hash = $2, cached_s3_key = $3, status = 'ready'
WHERE id = $1
RETURNING id, session_id, document_name, source_url, target_url, target_s3_key, content_hash, cached_s3_key, signed_s3_key, cms_s3_key, status, last_error, upload_attempts, signed_at, uploaded_at, created_at
`

type UpdateSessionDocumentAfterFetchParams struct {
	ID          uuid.UUID      `json:"id"`
	ContentHash string         `json:"content_hash"`
	CachedS3Key sql.NullString `json:"cached_s3_key"`
}

func (q *Queries) UpdateSessionDocumentAfterFetch(ctx context.Context, arg UpdateSessionDocumentAfterFetchParams) (SigningSessionDocument, error) {
	row := q.db.QueryRowContext(ctx, updateSessionDocumentAfterFetch, arg.ID, arg.ContentHash, arg.CachedS3Key)
	var i SigningSessionDocument
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.DocumentName,
		&i.SourceUrl,
		&i.TargetUrl,
		&i.TargetS3Key,
		&i.ContentHash,
		&i.CachedS3Key,
		&i.SignedS3Key,
		&i.CmsS3Key,
		&i.Status,
		&i.LastError,
		&i.UploadAttempts,
		&i.SignedAt,
		&i.UploadedAt,
		&i.CreatedAt,
	)
	return i, err
}

const updateSessionDocumentAfterSign = `-- name: UpdateSessionDocumentAfterSign :one
UPDATE signing_session_documents
SET cms_s3_key = $2, signed_s3_key = $3, status = 'signed', signed_at = now()
WHERE id = $1
RETURNING id, session_id, document_name, source_url, target_url, target_s3_key, content_hash, cached_s3_key, signed_s3_key, cms_s3_key, status, last_error, upload_attempts, signed_at, uploaded_at, created_at
`

type UpdateSessionDocumentAfterSignParams struct {
	ID          uuid.UUID      `json:"id"`
	CmsS3Key    sql.NullString `json:"cms_s3_key"`
	SignedS3Key sql.NullString `json:"signed_s3_key"`
}

func (q *Queries) UpdateSessionDocumentAfterSign(ctx context.Context, arg UpdateSessionDocumentAfterSignParams) (SigningSessionDocument, error) {
	row := q.db.QueryRowContext(ctx, updateSessionDocumentAfterSign, arg.ID, arg.CmsS3Key, arg.SignedS3Key)
	var i SigningSessionDocument
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.DocumentName,
		&i.SourceUrl,
		&i.TargetUrl,
		&i.TargetS3Key,
		&i.ContentHash,
		&i.CachedS3Key,
		&i.SignedS3Key,
		&i.CmsS3Key,
		&i.Status,
		&i.LastError,
		&i.UploadAttempts,
		&i.SignedAt,
		&i.UploadedAt,
		&i.CreatedAt,
	)
	return i, err
}

const updateSessionDocumentStatus = `-- name: UpdateSessionDocumentStatus :one
UPDATE signing_session_documents
SET status = $2, last_error = $3
WHERE id = $1
RETURNING id, session_id, document_name, source_url, target_url, target_s3_key, content_hash, cached_s3_key, signed_s3_key, cms_s3_key, status, last_error, upload_attempts, signed_at, uploaded_at, created_at
`

type UpdateSessionDocumentStatusParams struct {
	ID        uuid.UUID      `json:"id"`
	Status    string         `json:"status"`
	LastError sql.NullString `json:"last_error"`
}

func (q *Queries) UpdateSessionDocumentStatus(ctx context.Context, arg UpdateSessionDocumentStatusParams) (SigningSessionDocument, error) {
	row := q.db.QueryRowContext(ctx, updateSessionDocumentStatus, arg.ID, arg.Status, arg.LastError)
	var i SigningSessionDocument
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.DocumentName,
		&i.SourceUrl,
		&i.TargetUrl,
		&i.TargetS3Key,
		&i.ContentHash,
		&i.CachedS3Key,
		&i.SignedS3Key,
		&i.CmsS3Key,
		&i.Status,
		&i.LastError,
		&i.UploadAttempts,
		&i.SignedAt,
		&i.UploadedAt,
		&i.CreatedAt,
	)
	return i, err
}

const updateSessionDocumentTargetURL = `-- name: UpdateSessionDocumentTargetURL :one
UPDATE signing_session_documents
SET target_url = $2
WHERE id = $1
RETURNING id, session_id, document_name, source_url, target_url, target_s3_key, content_hash, cached_s3_key, signed_s3_key, cms_s3_key, status, last_error, upload_attempts, signed_at, uploaded_at, created_at
`

type UpdateSessionDocumentTargetURLParams struct {
	ID        uuid.UUID      `json:"id"`
	TargetUrl sql.NullString `json:"target_url"`
}

func (q *Queries) UpdateSessionDocumentTargetURL(ctx context.Context, arg UpdateSessionDocumentTargetURLParams) (SigningSessionDocument, error) {
	row := q.db.QueryRowContext(ctx, updateSessionDocumentTargetURL, arg.ID, arg.TargetUrl)
	var i SigningSessionDocument
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.DocumentName,
		&i.SourceUrl,
		&i.TargetUrl,
		&i.TargetS3Key,
		&i.ContentHash,
		&i.CachedS3Key,
		&i.SignedS3Key,
		&i.CmsS3Key,
		&i.Status,
		&i.LastError,
		&i.UploadAttempts,
		&i.SignedAt,
		&i.UploadedAt,
		&i.CreatedAt,
	)
	return i, err
}

const updateSigningSessionStatus = `-- name: UpdateSigningSessionStatus :one
UPDATE signing_sessions
SET status = $2, updated_at = now()
WHERE id = $1
RETURNING id, tenant_id, application_id, signer_role, callback_url, callback_secret, status, expires_at, created_at, updated_at
`

type UpdateSigningSessionStatusParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

func (q *Queries) UpdateSigningSessionStatus(ctx context.Context, arg UpdateSigningSessionStatusParams) (SigningSession, error) {
	row := q.db.QueryRowContext(ctx, updateSigningSessionStatus, arg.ID, arg.Status)
	var i SigningSession
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ApplicationID,
		&i.SignerRole,
		&i.CallbackUrl,
		&i.CallbackSecret,
		&i.Status,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
