// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tenants.sql

package repository

import (
	"context"

	"github.com/google/uuid"
)

const getTenant = `-- name: GetTenant :one
SELECT id, name, type, is_active, created_at FROM tenants
WHERE id = $1
`

func (q *Queries) GetTenant(ctx context.Context, id uuid.UUID) (Tenant, error) {
	row := q.db.QueryRowContext(ctx, getTenant, id)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}
