// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tenants.sql

package repository

import (
	"context"

	"github.com/google/uuid"
)

const createTenant = `-- name: CreateTenant :one
INSERT INTO tenants (name, type) VALUES ($1, $2) RETURNING id, name, type, is_active, created_at
`

type CreateTenantParams struct {
	Name string     `json:"name"`
	Type TenantType `json:"type"`
}

func (q *Queries) CreateTenant(ctx context.Context, arg CreateTenantParams) (Tenant, error) {
	row := q.db.QueryRowContext(ctx, createTenant, arg.Name, arg.Type)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const getTenant = `-- name: GetTenant :one
SELECT id, name, type, is_active, created_at FROM tenants
WHERE id = $1
`

func (q *Queries) GetTenant(ctx context.Context, id uuid.UUID) (Tenant, error) {
	row := q.db.QueryRowContext(ctx, getTenant, id)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}
